### ISSUE TITLE
Abstract all NAT traversal away from the user

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#103]
At the moment we have a few methods to control setting up the relay and udp hole punch (i.e. requesting it from a sepcific peer) but this should be done automatically without the users help.

Also, the `relayPeerPublicKey` should be removed from the `PeerInfo`

**Comment by CMCDragonkai** [comment]
This is related to #108, in order to abstract the hopping, we have to use the Kademlia system.
