### ISSUE TITLE
Quality of life improvements

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#107]
There are 4 main points to this as outlined in https://github.com/MatrixAI/js-polykey/pull/84#issuecomment-691671347 :
1. Quality of Life improvements and abstraction/modelling improvements and design improvements and standardisation and Quality Assurance stuff.
2. Proper model based testing and property testing using xstate-test and fast-check.
3. Spec sheet that can derive UML diagrams... and so on. Need to see how it all fits together.
4. Nix based integration testing.

**Comment by robert-cronin** [comment]
I would say this is largely done now, we have a lot of improvements in our domain modelling as well as our . We also now have a rough spec in the form of xstate machines for our most important transitions and hopefully later we can take that spec and use it in our implementation as well. UML diagrams are still not a thing, but we have our dependency graph which is looking much better now.

**Comment by CMCDragonkai** [comment]
Where's your new dependency graph?

**Comment by CMCDragonkai** [comment]
Post it on slack when you have it!
