### ISSUE TITLE
Kademlia DHT for multi-hop relay/NAT traversal

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#108]
This is kind of a cleanup as well as an extension of existing features. At the moment we have a NAT traversal based on public peers but a polykey node can have only one relay peer set. We want this to be completely abstracted away from the user.

Kademlia will provide this ability. Any node can act as a relay peer. Kademlia is usually used for content routing but in our situation, the content will be public keys of polykey nodes.

**Comment by CMCDragonkai** [comment]
The "relay" is just an ephemeral concept used encapsulated inside the pk system. It should never be exposed to the end user. The end user should not need to specify anything or know anything about relays UNLESS it's a special circumstance, or the user is doing something custom. Like ourselves Matrix AI.
