### ISSUE TITLE
Default port for TCP and UDP

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#109]
We have decided on a default port of `1314` for polykey but there is an issue of port conflicts if there are multiple pk instances serving on the same ip address. We need some way to check first if a port is taken. There might be a way to do this in gRPC but if not we can take some ideas from here: https://stackoverflow.com/questions/19129570/how-can-i-check-if-port-is-busy-in-nodejs/35251815#:~:text=Check%20out%20the%20amazing%20tcp,port%20is%20accepting%20connections%20tcpPortUsed.

**Comment by CMCDragonkai** [comment]
This is fine. One just does the default port and if it fails we error out and ask the user to provide a different port.

On 17 September 2020 1:32:57 pm AEST, Robbie Cronin <notifications@github.com> wrote:
>We have decided on a default port of `1314` for polykey but there is an
>issue of port conflicts if there are multiple pk instances serving on
>the same ip address. We need some way to check first if a port is
>taken. There might be a way to do this in gRPC but if not we can take
>some ideas from here:
>https://stackoverflow.com/questions/19129570/how-can-i-check-if-port-is-busy-in-nodejs/35251815#:~:text=Check%20out%20the%20amazing%20tcp,port%20is%20accepting%20connections%20tcpPortUsed.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/109

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
