### ISSUE TITLE
Defining 'random access' in polykey

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#11]
Traditionally, random access implies that granularity at the block level is available when accessing files. However, in Polykey files will be encrypted using pgp which does not offer this definition of random access. This means accessing any chunk of the file will warrant the entire being deciphered. This is okay since for the moment Polykey will mainly be dealing with small files.

From a different perspective, it does offer random access, but on a granularity of files. Compared to representing a secret bundle as a tar archive, which offers no random access, the current implement where a secret bundle is a directory of encrypted secret still offers accessing individual secrets without the need to decrypt everything the in the bundle.

In future, there is scope to allow random access on block level. One potential implementation is if the filesystem (i.e. the secret bundle) is represented as a file. The contents of the bundle can be block mapped, similar to traditional filesystems which are also stored in a one dimensional space (hard disk).

**Comment by CMCDragonkai** [comment]
Here are some examples of block allocators that we can use in the future:

* https://en.wikipedia.org/wiki/Memory_pool
* https://en.wikipedia.org/wiki/Orlov_block_allocator
* https://github.com/ipfs/go-sbs/blob/master/design.md
* https://github.com/arneg/GJAlloc
* https://github.com/ipfs/js-ipfs-block-service
* https://github.com/ipfs/js-ipfs-block

https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/ipfs-dag/

It the last parts involving IPFS would be quite interesting to see if Polykey secret bundles itself can piggy back of the IPFS protocols for their filesystem. What we end up is a decentralised filesystem kept secure and encrypted.

**Comment by CMCDragonkai** [comment]
Also wanted to re-iterate there are all sorts of "filesystems in a file" implementations around.

* Tar Archives
* HDF5

The key point about those is that they were not designed for read/write or random access. The best systems are actual filesystems backed by a file representing blocks. We started with those first, but then we have pivoted to considering more low level blocks. However if we only need file-level granularity of random access and writes, then we can piggy back off the host filesystem to achieve this.

**Comment by MeanMangosteen** [comment]
It has been decided that there will be random read/write access. The file will be split into blocks of a size defined by the user or defaults to certain size (4KB). 

This way the entire file does not need to be decrypted when reading or writing. Only the chunks relevant to the operation will ciphered and serialised to disk

**Comment by MeanMangosteen** [comment]
This has been implemented as described above. The plaintext is split in to 4096 byte blocks, each block is encrypted with a seperate and random IV using 256 gcm. The IV is prepended to the ciphertext to form a 'chunk'. That is, the first 16 bytes consisting of the IV, followed by the corresponding 4096 bytes of ciphertext.

**For writes of size < blocksize:** the chunk at the position being written to is decrypted, new data overlayed, encrypted with a new IV and finally persisted. If the write is at a position where the new data spans two blocks, the above process is applied to both affected blocks.

**For writes of size > blocksize:** The first and/or last block need to be overlayed like described above as they may not lie on block boundaries. The (potential) middle blocks will lie on block boundaries and also fill the entire block, so they do not need to be overlayed, they are simply encrypted and persisted directly.
