### ISSUE TITLE
Add json schema for request/response components in openapi spec

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#114]
In order to aid validation, we can replace the existing component definitions in `openapi.yaml` with json schemas, for example:
```
openapi: 3.0.1
info:
  title: ...
  description: ...
  version: 0.0.1
servers:
- url: /
tags:
- name: root
  description: Default namespace
paths:
  /ping:
    get:
      tags:
      - root
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    Pong:
      $ref: 'components/schemas/Pong.json'
```
and for `Pong.json`:
```
{
  "$schema": "http://json-schema.org/draft-00/schema#",
  "type": "object",
  "properties": {},
  "required": []
}
```
Note we have to use draft-00 as that is what openapi supports.

**Comment by robert-cronin** [comment]
I think this is now redundant, we don't have any schema's anymore, the new secret command is now using a post to `/secrets/<vaultName>/<secretName>` and the body is `text/plain`

**Comment by CMCDragonkai** [comment]
Shouldn't we allow application/octet-stream for arbitrary bytes?

On 13 October 2020 5:05:35 pm AEDT, Robbie Cronin <notifications@github.com> wrote:
>I think this is now redundant, we don't have any schema's anymore, the
>new secret command is now using a post to
>`/secrets/<vaultName>/<secretName>` and the body is `text/plain`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/114#issuecomment-707510774

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
I have added in `application/octet-stream` which provides a file upload button in the swagger docs, so we now have support for arbitrary bytes working nicely too :+1:
