### ISSUE TITLE
CLI unclear help message for `polykey vaults new`

### ISSUE THREAD

**Issue by nzhang-zh** [MatrixAI/Polykey#115]
Haven't checked other subcommands but the help message for `pk vaults new` does not mention required argument.

```sh
[nix-shell:~/matrix.ai/js-polykey]$ ./bin/polykey vaults new --node-path ~/.polykey
```

This does not return error but also doesn't do anything. Maybe nicer to get an error message?

```sh
[nix-shell:~/matrix.ai/js-polykey]$ ./bin/polykey vaults ls --node-path ~/.polykey
no vaults found
```

Realized I need to supply a vault name but help message does not indicate this argument.

```sh
[nix-shell:~/matrix.ai/js-polykey]$ ./bin/polykey vaults new -h --node-path ~/.polykey
Usage: polykey vaults new [options]

create new vault(s)

Options:
  --node-path <nodePath>  node path
  -h, --help              display help for command


[nix-shell:~/matrix.ai/js-polykey]$ ./bin/polykey vaults new myvault --node-path ~/.polykey
vault created at '/home/ning/.polykey/myvault'
```

**Comment by robert-cronin** [comment]
after discussion with @nzhang-zh, the command should also throw an error when there is no vault name specified which doesn't currently happen

**Comment by robert-cronin** [comment]
new vault command on cli has been changed to have a dedicated, required vault name parameter so it will alert you if its not specified:
```
➜  js-polykey git:(add-oath2) ✗ pk vaults new
error: required option '-vn, --vault-name <vaultName>' not specified
```
I've also added a `(required)` prefix to make it more clear which are needed from the help message:
```
Usage: polykey vaults new [options]

create a new vault

Options:
  --node-path <nodePath>         node path
  -vn, --vault-name <vaultName>  (required) unique name of the new vault
  -h, --help                     display help for command
```
