### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#12]
After seeing that key generation can take 30 seconds, and that kbpgp is async API based. I have realised that we will probably need multithreading to make this fast. Node now seems to have 2 solutions to the multithreading problem:

* https://nodejs.org/api/worker_threads.html
* https://github.com/audreyt/node-webworker-threads

It seems that the library is matching the webworker API maintaining some compatibility with browser based web workers (although this may not be a big deal). The problem is though is if we want to make this work in IOS and Android we have to consider how this will be impact it if we are reliant on these Node specific features. See: https://www.nativescript.org/faq/how-does-nativescript-run-my-javascript-code

**Comment by CMCDragonkai** [comment]
https://docs.nativescript.org/core-concepts/multithreading-model

It seems that this part of the code may be platform dependent. We may have to switch between different multithreading solutions depending on the platform.

**Comment by CMCDragonkai** [comment]
We're able to reuse what we did in EFS for js-polykey right?

Also is it possible to genericize what EFS does, so that the same thread pool can be shared between all parallel requirements. So if js-polykey needs to use a thread pool, that is the same thread pool as used by EFS.

This way we avoid having to create separate threadpools for every single component that will require parallelism.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
