### ISSUE TITLE
keypair generation command/pregenerating a keynode

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#120]
We might need to pre-generate a keynode and move it somewhere else (e.g. generating a keypair on a local machine and putting it in metadata to start an EC2 instance with). Currently there is only `pk agent init` command that also starts polykey and thus also automatically generates all the other folders needed to run polykey (.peers, .pki etc). Instead we just want to generate the keynode as that is all that is requried by polykey for initialization.
Another nice feature would be to automatically link the running keynode to the keypair just generated.

**Comment by CMCDragonkai** [comment]
Can you make sure all those directories are in 1 keynode state directory?

Also once in the subdirectory they don't need to be hidden folders. So no need for the dot prefix.

Only the default home directory needs the dot prefix. Everywhere else is user specified.

On 22 October 2020 3:54:07 pm AEDT, Robbie Cronin <notifications@github.com> wrote:
>We might need to generate a pre-generate keynode for moving to
>somewhere else without also generating everything else (e.g. generating
>a keypair on a local machine and putting it in metadata to start an EC2
>instance with). Currently there is only `pk agent init` command that
>also starts polykey and thus also automatically generates all the other
>folders needed to run polykey (.peers, .pki etc). Instead we just want
>to generate the keynode as that is all that is requried by polykey to
>start.
>Another nice feature would be to automatically link the running keynode
>to the keypair just generated.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/120

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
