### ISSUE TITLE
Backup Key File In Case User Forgets Keynode Passphrase

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#128]
make a key file for backup for unlocking the keynode - currently we only have root keypair (i.e. passphrase ). However the user can forget his passphrase and its better that we have a backup keyfile that could still unlock the keynode
@gideonairex

**Comment by robert-cronin** [comment]
I am actually not sure that kbpgp does anything like this natively but we can achieve similar functionality by storing a mirrored version of the vault keys in a separate file that is somehow protected by that backup key file

**Comment by robert-cronin** [comment]
I will add this into the next PR as I think it will be relatively straight forward to implement.

**Comment by CMCDragonkai** [comment]
We have a recovery code system similar to bip39 mnemonics. That should be sufficient to solve this problem. See the screenshots that @faithveloro has worked on.

**Comment by faithveloro** [comment]
Attaching screenshots here: 
![✳️ Desktop - Step 3 1_ Backup or Recovery Code](https://user-images.githubusercontent.com/46587577/101643995-a9d4ab80-3a6f-11eb-863f-597d7b8160b1.jpg)
![✳️ Desktop - Step 3 2_ Backup or Recovery](https://user-images.githubusercontent.com/46587577/101644029-b22ce680-3a6f-11eb-93c3-090da4f5b677.jpg)
![✳️ Desktop - Step 3 3 1_ Backup or Recovery](https://user-images.githubusercontent.com/46587577/101644057-b953f480-3a6f-11eb-997f-8eab5fb44f13.jpg)
![✳️ Desktop - Step 3 3 2_ Backup or Recovery](https://user-images.githubusercontent.com/46587577/101644071-bc4ee500-3a6f-11eb-8032-dc8f376efcd0.jpg)
![Desktop - Step 3 3 3_ Backup or Recovery Success](https://user-images.githubusercontent.com/46587577/101644089-bf49d580-3a6f-11eb-8d55-c709364fdf3f.jpg)

**Comment by robert-cronin** [comment]
I am currently integrating https://github.com/bitcoinjs/bip39 into the key manager for mnemonic generation, my one concern is that kbpgp keys are not currently deterministic (strictly speaking they are but not to us) because the salt/seed is not transparent or definable when generating a new keypair. So my alternative thought was to store this mnemonic in the KeyManager and then have the mnemonic maintain an encrypted copy of the vault keys on file (can do this with symmetric encryption) so if the user ever forgets their passphrase, the whole keynode can be restored via that encrypted file.

**Comment by robert-cronin** [comment]
another issue here is that the vault keys are currently stored in each vault to localise vault information as well as avoid large cryptographic operations on a single, centralised vault key file in the case of very many vaults. We can just maintain an encrypted file within each vault alongside the existing vault key.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
