### ISSUE TITLE
social discovery is not working as intended

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#131]
At the moment we have exposed `pk peers social` interface for finding peer users via social discovery services like keybase, but it is not working as intended and failing with an error of `fetch is not defined`. We will also need to find some way to put social proof on a user's keybase (our first integration) by means of a signed `polykey.proof` file in the user's public path so it can be directly access via a call to `https://<username>.keybase.pub/polykey.proof` as kbfs exposes this interface publicly.

Another enhancement might be to transfer the `social` sub command onto `pk peers find ...` instead of just `pk peers social ...` so as to disambiguate the meaning of the command from first glance.

Also less important, `-h, --handle` param is interfering with help command, I suggest renaming to `-hn, --handle`

**Comment by CMCDragonkai** [comment]
According to our new polykey-design and DI augmentation process, any social part of polykey needs to be abstracted using a strategy pattern. Basically any code that does social needs to be a like plugin. Other people can contribute new social plugins that can be included in a PK distribution or installed. For now we will release our own plugins. So keybase should be just one of the possible IdPs.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
