### ISSUE TITLE
The ability to launch $EDITOR when editing a file in a vault

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#139]
I'm not sure but is this available?

```
git config --edit
```

Will launch $EDITOR and wait till it closes (hopefully using read/writable fds, or it has to be a temporary file (but security is an issue here)).

I feel like we talked about this before.

Not a high priority feature.

@robert-cronin

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
