### ISSUE TITLE
Data Integrity and Authentication

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#14]
It would be desired if we can offer guarantees to some level that the encrypted data has not been tampered with. 

Some possibilities would be using HMAC or cipher modes such as GCM with built-in data integrity mechanisms.

**Comment by MeanMangosteen** [comment]
This may introduce overheads, so it would be fitting that the feature be optionally enabled by the user.

A quick case study of current solutions:
EncFS [uses HMAC](https://github.com/vgough/encfs/blob/master/DESIGN.md)
GoCryptFS uses[ GCM with additional authenticated data](https://nuetzlich.net/gocryptfs/forward_mode_crypto/) (what is this?) 
CryFS [uses gcm](https://www.cryfs.org/howitworks)

**Comment by CMCDragonkai** [comment]
GCM may do this automatically. And if so, we can close the issue.

**Comment by MeanMangosteen** [comment]
GCM is an authenticated encryption with associated data ([AEAD](https://en.wikipedia.org/wiki/Authenticated_encryption)) scheme. This means it does in fact provide data authentication which implies data integrity. It uses [Galois Field](https://en.wikipedia.org/wiki/Galois_field) multiplication for authentication.

The 'with associated data (AD)' part means that you can feed additional data into the algorithm to tie the ciphertext to some context. This is so

> attempts to "cut-and-paste" a valid ciphertext into a different context are detected and rejected

Most commonly, the AD would be the header of an encrypted network packet, but in our case the AD could be the filename and/or metadata which would bind it its ciphered file data.

**Comment by CMCDragonkai** [comment]
Do we need an implementation issue then?
