### ISSUE TITLE
Add 'lightweight' primitive connection functions (ping)

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#149]
Fundamental network functions ('PING', relaying a message, etc) require a heavyweight connection construction.

For example, in `NodeGraph:getClosestGlobalNodes()`, we only add discovered nodes to our buckets database once we deem the node to be 'active' or 'online'. The Kademlia specification suggests to perform a ping operation to determine whether a node is active. However, our current network implementation requires NAT punching to create a connection to a node before we can even determine if the node is active. Thus, for a simple operation, it requires a significant degree of overhead.

A lightweight mechanism for pinging another node (without requiring this heavy network construction) would be beneficial.

**Comment by joshuakarp** [comment]
Regarding `PingNode` (from nodes CLI MR: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/198#note_635093912):

> So connection establishment is a bit heavy right now? Why is this? Assuming 2 nodes already exist, they already have forward and reverse proxies. It's just a matter of constructing the NodeConnection?
> There is some optimisation possible in the network domain relating to timeouts/delays for sending the punch packets. I had set it to a safe 1000ms, but that can be reduced to reduce the latency.
> Remember everything we can limit via the ACL. It's just a matter of adding additional permission actions to the gestalt and checking for them. The check for them should be done in the GRPC service handlers.
> However if the domains are mutating the ACL, such as the case with GestaltGraph, then the checking of the ACL can also be done inside the domains. We should be consistent here, I'm not sure if I made a design decision on this.

As such, we may not need to consider this.

**Comment by CMCDragonkai** [comment]
I think you already did this didn't it? In that case, it should go into review.

**Comment by joshuakarp** [comment]
@CMCDragonkai this was more of an issue for investigation any ways that we could improve the efficiency of some of our networking operations (e.g. pinging a node). But given your quoted comment from above, this may not be necessary.

**Comment by CMCDragonkai** [comment]
As soon as we establish a connection at the networking domain without even the GRPC establishment. Then this can be considered a ping success.

**Comment by CMCDragonkai** [comment]
Avoid GRPC establishment, just try to open a connection on the Forward Proxy and connect this to the `pk nodes ping` CLI command.

**Comment by CMCDragonkai** [comment]
Close this issue when done.

**Comment by joshuakarp** [comment]
> Avoid GRPC establishment, just try to open a connection on the Forward Proxy and connect this to the pk nodes ping CLI command.

Comment for myself: see `NodeConnection.start` for how we currently do this. We call `fwdProxy.openConnection` already there. But we want to do this without needing to setup and start a `GRPCClient`.

Obviously, if the `NodeConnection` object already exists, and we want to check whether the node is still active, we can just use the existing `nodes ping` implementation.

**Comment by joshuakarp** [comment]
Ping node no longer establishes a `GRPCClient`: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/184/diffs?commit_id=fffcbb5126d24b3e0de767a91ad97aabf90887f7
