### ISSUE TITLE
Atomic Writes/Consistent Writes in the Lower FS

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#15]
The lower fs provides the persistence of writes to our "files" in Polykey. We allow incremental mutation of "files" in Polykey. So that means given a 1 GiB file, editing the middle of the file doesn't mean rewriting the entire file. It's supposed to just edit and mutate that small partition in the middle.

However let's say that the buffer we are writing into the middle is 10 MiB. Then the problem is that when passing 10 MiB into the lower FS which is backed by the Node FS, that results in potentially multiple calls to the `write` syscall. And multiple write syscalls are not atomic. So that means it is possible to corrupt the encrypted ciphertext backing the plaintext file.

We want to make sure that we have "consistent" updates to our ciphertext files so we don't leave it in an inconsistent state. That would be quite bad.

There are a couple ways of doing this:

1. Write to temporary and perform atomic rename. (This defeats the purpose of incremental mutation)
2. Some sort of COW system

We should look into databases and ACID implementations for some ideas here.

---

It appears that using Git should mean this is not a problem for us. Because we don't care atomicity on a block basis or even on a single ciphertext basis. We only care about atomicity from 1 commit transaction to another. So if something fails in the middle of a commit transaction. An automatic rollback should be made.

**Comment by CMCDragonkai** [comment]
@ll-aashwin-ll https://unix.stackexchange.com/questions/464184/are-file-edits-in-linux-directly-saved-into-disk

We should ensure that we fsync before performing any automatic commits. I wonder what atomicity guarantees exist in isomorphic-git.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
