### ISSUE TITLE
Duplex streaming generator issues

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#151]
_Created by @DrFacepalm_ 

There exists an issue with duplex streaming:
```
1. Client writes message to server through C-S stream
2. Server reads from C-S stream
3. Client writes null to server through C-S stream
4. Server attempts to read from C-S stream and gets null, and handles it. (This marks the end of the client writes)
5. Server should then be able to write messages back to client
6. Server attempts to write on the S-C stream, but finds that it is destroyed.
```

Currently, the code is using callbacks, and using on `data` and on `end` events to deal with the data. and is working fine, however it would be nice to use the generators.

Related file: `./src/grpc/utils.ts`

**Comment by CMCDragonkai** [comment]
This is now solved. It's no longer a problem.
