### ISSUE TITLE
Stop using `gh-pages` and instead just generate docs into master

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#160]
Docs generation should be done in master branch now to avoid having to synchronise to gh-pages all the time. This represents reference documentation for the library and should be linked in the wiki.

The github repo also allows master branch to be the one used now.

**Comment by CMCDragonkai** [comment]
This is now done in TypeScript-Demo-Lib, so we can just use `./docs` here in master branch instead of `gh-pages`.

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you do this as well for https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/206. Then you can move this for review.

**Comment by CMCDragonkai** [comment]
I've changed the settings here:

![image.png](https://images.zenhubusercontent.com/604ac1248439e60802e3f597/d3892838-aaa0-4843-9fbe-035bf0408f68)

All you need to do is adjust the docs generation to the same way that TypeScript-Demo-Lib does it.

**Comment by CMCDragonkai** [comment]
@tegefaulkes just have a look at the `npm run docs` command from TypeScript-Demo-Lib repo.

**Comment by tegefaulkes** [comment]
I've just had a look at js-polykey. it already has the script for docs. `"docs": "typedoc --out ./docs src && touch ./docs/.nojekyll",`.
what exactly do I need to change here if anything? @CMCDragonkai

**Comment by CMCDragonkai** [comment]
That should be it. You can try later. Our code isn't using the same doc standard yet but it should.

**Comment by CMCDragonkai** [comment]
Since this is now done in the settings and MR206 is merged. It should be working as soon as client-refactoring is merged.
