### ISSUE TITLE
Cannot establish a gRPC connection when using Apple M1 processor

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#167]
_Created by gideonairex_

### Environment
1. Mac - Big Sur
2. Processor - Apple M1

### Current
1. Everytime the client connects it hangs up
2. Then drops the connection

### Expectation
1. Client should connect to the gRPC server

### Screenshots
![image](https://user-images.githubusercontent.com/49772421/119911574-e3a55a00-bf9c-11eb-982d-d2c7fbbf99cd.png)
![image](https://user-images.githubusercontent.com/49772421/119911586-e7d17780-bf9c-11eb-8c63-73b4bede42fe.png)
![image](https://user-images.githubusercontent.com/49772421/119911592-eacc6800-bf9c-11eb-9da4-753e31d43e1d.png)
![image](https://user-images.githubusercontent.com/49772421/119911596-ed2ec200-bf9c-11eb-928e-d751ae50822f.png)

**Comment by CMCDragonkai** [comment]
I'm going to close this issue for now as we don't support Apple M1 yet.
