### ISSUE TITLE
Add password generator

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#176]
_Created by @CMCDragonkai_

When users create secrets automatically (for example, when creating an account password on a website), we should have some mechanism that generates a secure password.

For example, in LastPass:

![image](https://user-images.githubusercontent.com/49772421/119923426-080d3080-bfb5-11eb-86f6-58f13db5934e.png)

This can also be used for generating Polykey secrets. For this case, we should use bip39: https://github.com/bitcoinjs/bip39

**Comment by CMCDragonkai** [comment]
Closed in favour of #34.
