### ISSUE TITLE
Update testnet.polykey.io to point to the list of IPs running seed keynodes

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#177]
Done on cloudflare.

![image](https://user-images.githubusercontent.com/640797/119934900-e8ccce00-bfc9-11eb-84b6-dba70b5eb1a5.png)

This will depend on us deploying the js-polykey keynode containers onto AWS.

Also change `bootstrap.polykey.io` to `seed.polykey.io`.

**Comment by CMCDragonkai** [comment]
@joshuakarp we have agreed to use the term "seed" rather than "bootstrap" or "broker".

So this should now be called `seed.polykey.io` and all other uses should be seed.

**Comment by joshuakarp** [comment]
Uses of `broker` still needs to be refactored as `seed` throughout the nodes domain.

**Comment by joshuakarp** [comment]
Furthermore, I should remove the separation of `brokerNodeConnections` to just be normal `nodeConnections`. Seed nodes are just nodes that we provide to a new keynode to "introduce" the keynode to the larger Polykey network. They aren't special. See a previous message from me for context:

> There's a couple of reasons why the brokers are separate:
> * To establish a connection to them, it's assumed a direct connection is possible (so no need for hole-punching)
> * I don't add their details into the buckets database at all. I believe my assumption was that they are probably going to be 'owned' by us as Matrix AI, and they shouldn't be discoverable by other nodes (from getClosestGlobalNodes)
> 
> I know you said before that the broker nodes could be any node in the network though, and thinking about this some more now, it would probably make sense for these nodes to just be integrated like any other node. Unless we are treating them as something special (like a central 'Polykey' keynode)

**Comment by CMCDragonkai** [comment]
So no both `bootstrap` nor `seed`.

The `mainnet` and `testnet` is more explanatory.

**Comment by joshuakarp** [comment]
This issue is also related to #269.

**Comment by joshuakarp** [comment]
Start date changed from Nov 12th to Nov 18th (based on delays in #231).

**Comment by joshuakarp** [comment]
Start date changed from Thursday Nov 18th to Monday Nov 22nd (delays in #269, #231, and CLI MR on Gitlab).

**Comment by joshuakarp** [comment]
Start date changed from Mondya Nov 22nd to Thursday Dec 2 (delayed from refactoring work in #283).

**Comment by CMCDragonkai** [comment]
The `testnet.polykey.io` now points as a CNAME record to `polykey-testnet-71241bf1071fde8f.elb.ap-southeast-2.amazonaws.com`.

![testnet polykey io](https://user-images.githubusercontent.com/640797/177314101-1004f84e-8fba-47ac-b272-3b776ebc0748.png)

It is DNS only because, all we are doing is forwarding the NLB IPs to `testnet.polykey.io`, no caching is necessary, the whole thing is an API. Also since there's no proxy enabled, then there's no cloudflare TLS being used here. Instead connections to the agents will be end to end encrypted to the agent task itself. It will be important that the NLB load balances in a sticky way according to the origin IP and port, so they hit the same ECS task.

```
[nix-shell:~/Projects/Polykey-Infrastructure]$ nslookup testnet.polykey.io
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
testnet.polykey.io	canonical name = polykey-testnet-71241bf1071fde8f.elb.ap-southeast-2.amazonaws.com.
Name:	polykey-testnet-71241bf1071fde8f.elb.ap-southeast-2.amazonaws.com
Address: 13.54.143.110
Name:	polykey-testnet-71241bf1071fde8f.elb.ap-southeast-2.amazonaws.com
Address: 52.64.204.161
Name:	polykey-testnet-71241bf1071fde8f.elb.ap-southeast-2.amazonaws.com
Address: 54.66.209.134
```

**Comment by CMCDragonkai** [comment]
Renamed this issue to focus only on `testnet.polykey.io`. This is done now, and we would want to configure Pulumi to auto update the `testnet.polykey.io` DNS to any new NLB DNS that gets created.

**Comment by CMCDragonkai** [comment]
Mainnet deployment will be separate piece work.
