### ISSUE TITLE
EFS asyns calls may not be truly async

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#18]
As of now, the async calls in the EFS have been wrappers around the sync functions. The sync functions implement all the logic to carry out the the corresponding functionality of the corresponding function and its async counterpart would util process.nextTick(...) to make it async. 

However, calling process nextTick() may only push the top level sync function to the event queue. Imagine if the sync function calls further sync functions, when the top-level sync function runs, there is nothing to enforce the nested sync functions run in an async manner.

For example, the efs.writeSync() calls fs.writeSync(). If the above hypothesis is true, then a call to efs.write() would schedule efs.writeSync() to run async'ly but when it actually run, it would still be calling fs.writeSync() thereby blocking the main thread. In particular for large writes there will be a performance penalty. This is an issue because efs.write() is not actaully truly async.

To test this we can use a snippet:

```
process.nextTick(() => { //A
  fs.writeSync(50MiB);
  console.log('finish write');
});

process.nextTick(() => {  // B 
  console.log('async console log);
});

console.log('sync console log) // C

---

fs.write(50MiB, () => {  // A
  console.log('finish write');
});

process.nextTick(() => {  // B
  console.log('async console log);
});

console.log('sync console log) // C
```
If the above is true, then we would expect the order of completion to be C -> A -> B in the first instance; C -> B -> A in the second.

If it turns out that the second one is correct performance, then that means sync efs needs to call sync functions, but async efs needs to call sync functions from VFS, but async functions from native fs.

**Comment by CMCDragonkai** [comment]
The resolution for this issue involves rewriting some of the async versions of EFS functions?

**Comment by CMCDragonkai** [comment]
Will it be a big rewrite or a smaller rewrite? How much code are talking about here?

**Comment by MeanMangosteen** [comment]
Well one naive solution for the rewrite of async functions, would be to copy the sync function and just replace the sync calls with async ones.

Even if there are large additions in terms of code, the only time spent would be to restructure a few lines to accommodate the new async calls.

But perhaps there is a more elegant way to go about it.

**Comment by MeanMangosteen** [comment]
Confirming our assumptions. 
When utilising process.nextTick() for writes, the output:
```
sync console log - C
finish write - A
async console log - B
```
When using async write():
```
sync console log - C
async console log - B
finish write - A
```

**Comment by MeanMangosteen** [comment]
To shed some light the this matter: node isn't exactly single threaded. There is the event loop which runs on one thread. At the core of the event loop is a semi-infinite loop utilising the host's OS event notification facilities. For example on linux this is epoll. This is all abstracted away by libuv allowing node to use the same api to interact with system resources across all platforms.

So everything that runs in the event loop *should* be epoll-able. This includes things like sockets, timeouts, signals. There is nothing stopping one from running blocking or long-standing operations on the event loop thread, but this would mean that the task would hijack the thread, and progress may not be made on other tasks.

However there are somethings which the OS does not provide non-blocking operations for. Like the I/O for regular files. For this reason, the 'fs' module has libuv simulate the non-blocking behaviour by having a separate thread pool (by default 4), to offload file I/O from the event loop. If it didn't do this, there would be only a synchronous api for the 'fs' module.

So mostly like the async flavour of the methods in the 'fs' module are by separate worker threads, not in the event loop. While the sync variant runs the event loop.

process.nextTick() simply schedules a function to run almost immediately, within the same iteration of event loop (setImmediate() ironically runs it in the next iteration).

So when the fs.writeSync() is called in  nextTick(), it blocks the event loop and not allowing other tasks to run. Hence we see the order that we see.

**Comment by MeanMangosteen** [comment]
Current async EFS methods have been implemented using native 'fs' async methods. Future EFS methods will follow suit. This issue can be closed.
