### ISSUE TITLE
Maintaining cryptolinks of digital identities through a sigchain

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#181]
Digital identities are a key part of the gestalt structure. We use cryptolinks to state that keynodes have 'ownership' of a digital identity.

Recall that we have a chain of certificates for a particular keynode. Our cryptolinks are currently stored in the actual certificate itself.

Instead of recreating the entire certificate whenever a new digital identity is augmented with the keynode, or when a digital identity changes, we could instead remove the cryptolinks from the certificate altogether and maintain their existence through an additional **sigchain**. 

That is, along the chain of certificates, we have an additional **sigchain** at each certificate that stores the cryptolinks themselves.

Some core things to consider:
1. These chains should also map back to the previous certificates in the chain too (in order to verify with any of the valid root keys). That is, we can still verify a sigchain with a prior root key if it's still valid (e.g. a key refresh).
2. Log of claims: we should keep a log of claims made by the identities. This log should be a basic list, with the most recent additions at one end of the list. For an optimisation, we should also include an additional map, that maps digital identity IDs to their corresponding index in the log. This would make our operation more write-heavy, but provides a read optimisation (instead of having to iterate through the whole list, can simple query the map).

**Comment by CMCDragonkai** [comment]
This is done in client-refactoring now.
