### ISSUE TITLE
Extend the capcability control (the allowable actions) specified by the ACL

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#186]
@CMCDragonkai : https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/188#note_592046967

> We need to map out exactly what kind of permissions we will be having here. All permissions below can be thought as allowable actions that the other node can do.
> 
> 1. Send Notification - allow the other node to send a notification to us
> 2. To pull/clone a particular a vault - has to specify which vault we allow
> 3. To allow the node to scan for pullable vaults
> 4. To allow one to push a particular vault
> 
> For now we can focus on just the 3 top permissions. The push mechanism we have to figure out later.
> 
> The pull mechanism has to specify a specific vault to be pullable, this is where it gets a bit complicated.

**Comment by CMCDragonkai** [comment]
This is done enough until we have a more specific requirements.
