### ISSUE TITLE
Incorporate subleveldown, transaction pattern, and serialize encrypt into all subdomains

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#187]
Currently our subdomains use a conglomerate of different variations of leveldb, encryption, and control of actions on the database. In the recently introduced ACL subdomain, the expected use of these has been implemented. We can use this as a framework for how we should structure the other subdomains.
* Incorporate subleveldown: usage of a top-level database for the entire subdomain, breaking down into lower levels for other database usages in that domain. For example, the gestalts subdomain previously used a prefixed key to specify separate levels in the database. This has recently been changed to also use subleveldown. The same should be done for all other subdomains. In the future, this could also potentially allow us to provide a single leveldb for all domains, and simply separate the subdomains (gestalts, nodes, etc etc) into separate subleveldowns. This would allow us to perform cross-domain transactions and atomic operations.
* Transaction pattern: see ACL source
* Serialize encrypt: see ACL source (@CMCDragonkai can also comment on these latter 2)

---

Domains to be refactored:

- [x] IdentitiesManager - @joshuakarp 
- [x] SessionManager - @DrFacepalm 
- [x] Sigchain (+ change sequence number key to use lexicographic integers) - @joshuakarp

**Comment by CMCDragonkai** [comment]
In client refactoring this is done for DB, ACL, GG.

We are going to apply it to notifications and VM as well.

And any others. The only one that isn't is the key manager which will require its own database.

**Comment by CMCDragonkai** [comment]
I believe this is done for nodes domain as well. And @scottmmorris has done this for the vaults domain.

Still to do:

* IdentitiesManager - for tokens
* SessionManager

There's also the keys domain which currently the DB depends on, I have a plan for making KeyManager also use DB, but that means DB is managing the DB key outside of leveldb.

**Comment by joshuakarp** [comment]
Also to add, still to do:
* Sigchain (as well as porting the sequence number keys over to lexicographic integers, like the nodes domain)

**Comment by joshuakarp** [comment]
Added these domains as todos in the top-level description.

**Comment by joshuakarp** [comment]
`Sigchain` also needs to be refactored too (+ changing the sequence number key to use lexicographic integers)

**Comment by CMCDragonkai** [comment]
@joshuakarp did you do it for the IdentitiesManager?

BTW in the future this issue should be a Development spec, and then the checklist is actually in the PR/MR.

**Comment by joshuakarp** [comment]
@CMCDragonkai I haven't had a chance yet. 

Re the checklist, didn't we say last meeting that issues should always have a task list? i.e. every issue template has a checklist

Unless its a **Design** issue, where tasks may not be elicited quite yet, I feel that issues should always have a task list.

**Comment by CMCDragonkai** [comment]
Yea so development issues can have a checklist as well the PRs fixing them. But sometimes you need to write a task list that is copied to the PR and so therefore the checklist is on the PR not on the issue.

So I'm differentiating the checklist from tasklists. Checklists have checkboxes.

**Comment by CMCDragonkai** [comment]
@DrFacepalm I think he has done it for SessionManager.

**Comment by joshuakarp** [comment]
Ah gotcha - I didn't realise the distinction between checklist and tasklist. That makes sense.

**Comment by CMCDragonkai** [comment]
For KeyManager, it requires some special work if we want to do this.

> I want to make the KeyManager stateless with respect to its leveldb usage. Right now DB is storing its key in KeyManager, but it should be easier to instead make the DB encrypt its database with a db key that is encrypted by the KeyManager and stored on disk instead. That means you have the root key encrypted by the root password, and also the db key on disk which is encrypted with the root key. Basically the relationship between KeyManager and DB is kind of weird right now... there should be a way to simplify it. Not sure.

**Comment by DrFacepalm** [comment]
The session manager task should be completed  by this. https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/189, if this gets merged.

**Comment by CMCDragonkai** [comment]
Last things are:

* sigchain
* notifications

@emmacasolin you're also using DB for this one.

**Comment by joshuakarp** [comment]
`sigchain` DB integration finished in !195. `IdentitiesManager` has already been done by @CMCDragonkai

**Comment by CMCDragonkai** [comment]
For notifications this is addressed in #192. So we can close this now.
