### ISSUE TITLE
Notifications subsystem

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#192]
The notifications subsystem allows nodes from different gestalts to send messages to each other.

This is the way that users can tell other gestalts that they have shared a vault with them.

* Number of messages must be limited possibly 10,000, afterwards the messages are dropped
* Must use the ACL notify permission action
* Need to consider that once a message is read by any, that message is kept around in the notification queue, but is considered to have been read

See https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/204

Specification (from node notifications MR!161 in js-polykey):
* Agent GRPC exposes sendMessage and readMessage.
* Node GRPC exposes receiveMessage.
* Client will trigger sendMessage to Agent.
* Agent then connects to the node using NodeId and triggers a Node GRPC which is recieveMessage.
* Other Agent will push messages to the Notification object.
* Other Client can now shift all messages from the Notification object using readMessage that is a GRPC stream.

Note: gPRC calls should follow style outlined in #218

TODO
* New domain `notifications`
* Create `Notification` class
* Inject `ACL`, `DB`, `NodeManager` as dependencies
* Create the send and receive calls
* Make a limit on the number of messages allowed
* Check the ACL for permissions
* Create the Agent GRPC calls to receive messages
* Use the `NodeManager` to send out messages
* Create tests for `Notification` class
* Create `pk notifications` sub commands to introspect notifications
* You might want to have a "read" status attached to each message indicating
* Create tests for the `pk notifications`

**Comment by CMCDragonkai** [comment]
When using the NodesManager, this is just making a call to send a message.

The `Notifications` will probably need the `NodeManager` as a dependency injection.

**Comment by CMCDragonkai** [comment]
You do need to use the `ACL` to see if the there is a `notify` permission allowed on nodes trying to contact you.

**Comment by emmacasolin** [comment]
Some previous work on the notifications was done in these two MRs:
https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/146 - discussion of capabilities/potential implementations + a bit of code
https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/161 - copy of above but actually merged

**Comment by CMCDragonkai** [comment]
That means there may be old code src-old you should check in case there are parts to lift to src. But make sure our new notifications are using all the latest patterns of transactions, Async start and stop... Etc.

On 12 July 2021 10:55:27 am AEST, emmacasolin ***@***.***> wrote:
>Some previous work on the notifications was done in these two MRs:
>https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/146
>- discussion of capabilities/potential implementations + a bit of code
>https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/161
>- copy of above but actually merged
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/192#issuecomment-877895443

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
A merge request has been created for this issue: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/204

**Comment by CMCDragonkai** [comment]
You can store the count of the number of messages you have received in the domain-level DB. Then you create a sub level to store the actual messages.

Example see how ACL does it:

```
  protected notificationsDbDomain: string = this.constructor.name;
  protected notificationsMessagesDbDomain: Array<string> = [this.notificationsDbDomain, 'messages'];
  protected notificationsDb: DBLevel<string>;
  protected notificationsMessagesDb: DBLevel<NotificationId>;

      const notificationsDb = await this.db.level<string>(this.notificationsDbDomain);
      const notificationsMesssagesDb = await this.db.level<NotificationId>(
        this.notificationsMessagesDbDomain[1],
        notificationsDb,
      );
```

Use the `notificationsDb` to store domain-level dynamic configuration like the counter of messages.

The messages need to be ordered with respect to time. So you'll need a `monotonic-lexicographic-integer`. https://github.com/vweevers/monotonic-lexicographic-timestamp

Then if the messages exceeds the max limit, you can garbage collect old messages by dropping them (deleting them) from the message sub level.

**Comment by CMCDragonkai** [comment]
Also denial of service is reduced because you must trust the other gestalt which relies on the `notify` permission.

**Comment by emmacasolin** [comment]
> The messages need to be ordered with respect to time. So you'll need a `monotonic-lexicographic-integer`. https://github.com/vweevers/monotonic-lexicographic-timestamp

@CMCDragonkai should this be installed as a dependency or a devdependency?

**Comment by CMCDragonkai** [comment]
It should be a dependency.

**Comment by CMCDragonkai** [comment]
@emmacasolin hit some difficulties with the iteration of the database. @DrFacepalm is looking into this by Friday and try to get as much done over the weekend as well.

**Comment by CMCDragonkai** [comment]
@emmacasolin @DrFacepalm how is this going? What's the final remaining set of tasks?

**Comment by CMCDragonkai** [comment]
Schedule this for merging (even if not entirely clean) for Monday.

New things can be assigned on top of this based on review of issues generated from Nodes CLI.

**Comment by CMCDragonkai** [comment]
Any follow-up issues regarding this issue since merging?

**Comment by emmacasolin** [comment]
> Any follow-up issues regarding this issue since merging?

Nothing that I'm aware of, although I haven't been working on the code base since merging so others may be more likely to have run into issues if they're there

**Comment by CMCDragonkai** [comment]
Yea I haven't got around to reviewing the notifications yet. But since 
you'll be heading into #213, that will basically lead us to fully 
reviewing nodes, sigchain and notifications together.
