### ISSUE TITLE
Automatic Release Builds using vercel/pkg

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#193]
Releases will be a manual thing on GitHub.

However on master, every commit should automatically trigger a release build that will be published as a prerelease.

This is currently done on TypeScript-Demo-Lib, and needs to be ported over to this repository.

This repository has a number of challenges:

* Static assets like the bootstrap certificates (that may be resolved by importing these as typescript modules)
  - This may further be simplified if we can just use NodeIds and pre-programmed domain names/IP addresses rather than the full certificate
* Native modules like utp-native, leveljs, grpc-js

This will require understanding how vercel/pkg chooses the native modules to be used, debugging its snapshot filesystem, and seeing where assets are placed.

The node runtime of vercel/pkg is about 32 - 33 MiB. The TypeScript-Demo-Lib adds 1 MiB for the JS code. It will be interesting to see how large the js-polykey codebase will be. If it is quite big we should also include 2 additional optimisations:

* Minification applied to the `dist` directory (but without using webpack)
* Compression on the final executable, this is available as brotli or gzip compression option on the pkg command

But let's see how big they are, the js-polykey CLI executable shouldn't be that big!

**Comment by CMCDragonkai** [comment]
Note that prereleases are not official releases.

Official releases should be manually done with a proper changelog.

**Comment by CMCDragonkai** [comment]
Should start on this asap for client-refactoring branch.

**Comment by CMCDragonkai** [comment]
@tegefaulkes assigned this to you, you should be able to start on this now.

**Comment by CMCDragonkai** [comment]
Move this to review/QA when you're ready.

**Comment by CMCDragonkai** [comment]
The next thing will be commercial and website distribution, we will need to have some way for users to easily download from polykey.io.

**Comment by tegefaulkes** [comment]
Progress so far:
- pkg is working with the included native modules. some warnings about Jose but I think that's working. 
- currently setting up the gitlab-ci and nix-build. running into odd issue with  node-gyp-build trying to build `/usr/bin/env`

```
sh: /nix/store/i522y1a9g26fk6728v7arilshk4ph33z-node__at_matrixai_slash_polykey-0.0.41/lib/node_modules/@matrixai/polykey/node_modules/.bin/node-gyp-build: /usr/bin/env: bad interpreter: No such file or directory
```

**Comment by CMCDragonkai** [comment]
Can you link the branch where you're doing the experiments here.

**Comment by tegefaulkes** [comment]
The Typescript-Demo-Lib that works is; https://github.com/MatrixAI/TypeScript-Demo-Lib/tree/pkg-integration
The js-polykey branch I'm testing in is; https://github.com/MatrixAI/js-polykey/tree/pkg-integration

**Comment by CMCDragonkai** [comment]
Going to close this given that MR 206 is merged.

Proper testing to be done at the end!

**Comment by CMCDragonkai** [comment]
Only after client-refactoring is merged to master, will start to see CI/CD builds appear.

At that point we will need establish manual Q&A process for those published executables. They are set as pre-releases, so we will just do it manually for now, and later in the future automate tests against executables in different envrionments.
