### ISSUE TITLE
Re-enabling Dependency Type Checking - Readable Stream Type Errors

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#198]
We should re-enable the dependency type checking as this should ensure that our dependencies are also correctly typed.

We currently use:

```
    "skipLibCheck": true,
```

To avoid checking the types of our dependencies.

ATM, the readable-stream has type errors however this was fixed upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44828

We should be able to remove the line and renable checking the types of all of our work including dependencies.

Background context: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/issues/238

**Comment by CMCDragonkai** [comment]
@tegefaulkes you might as well check this too.

**Comment by tegefaulkes** [comment]
I removed `"skipLibCheck": true,` from the `tsconfig.json`. It builds fine.
So this issue is resolved unless the error occurs elsewhere besides building.

**Comment by CMCDragonkai** [comment]
Ok this can be closed when you merge the async tests MR.

**Comment by tegefaulkes** [comment]
!202 has been merged fixing this. closing issue.
