### ISSUE TITLE
Upload Directory (recursively) to a Vault

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#203]
### Requirements of this design

1. PK vaults should be able to accept an entire directory of secrets
2. The Vault system will need to be able to recursively iterative over the directory and copy recursively the directory into the vault
3. It is the equivalent of doing `cp -R ./somedir pk://somevault/somedir`
4. Does not need to work on clients that are on remote hosts for now

### Additional context

* https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey/-/issues/70

### Specification

1. Direct file path upload, and directory upload work on the host that the PK agent is running on
2. The vault must have function calls that accept a file path or a directory path
3. When the CLI or GUI client calls this, it should just pass the path of the directory to the vault manager
4. The recursive copy must also copy hidden files
5. It should ignore files that are not proper files
6. It needs to forgive errors and continue copying even if it fails on particular file (partial success is allowed)

**Comment by scottmmorris** [comment]
Functionality for this already exists, in the `addSecretDirectory` function. The CLI command takes in an on disk path to a directory and send via grpc to the agent. The agent then passes this into the `addSecretDirectory` function which recursively reads this directory on the agents disk. The GUI I think should be able to make use of this function in `Vault.ts` as well

**Comment by CMCDragonkai** [comment]
Do you have tests for this?

**Comment by scottmmorris** [comment]
There were tests but not extensive, I've added a few more. Also the function did not preserve the existing paths within the given secret directory which has been changed now. I have also implemented the partial success, with the logger emitting a warning message if an error occurs while adding a secret. So Ill close this issue now
