### ISSUE TITLE
Gestalt Discovery Integration into Identities and Nodes CLI

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#206]
### Specification

* Gestalt Discovery is the implementation of our social discovery theory/concept
* Gestalt Discovery involves using `links`/`claims`, `identities`, `sigchain`, and `nodes` domain as dependencies
* The discovery is triggered by search requirements and sharing usecases
  - Finding other identities that are augmented
  - To be able to share with an identity, that identity must be linked to a node in a gestalt
* The discovery interface is therefore in the CLI
* The `pk identities ...` subcommand must be capable of triggering the discovery process and augmentation process
   - `pk identities authenticate github.com` - should authenticate with a provider id and create a token for a given identity, it should tell the user what identity has been authenticated, as well as token information like expiry date if available
   - `pk identities augment github.com cmcdragonkai` - this augments `cmcdragonkai`, should fail if this account is not authenticated
* The `pk nodes ...` subcommand should focus on being introspective of the newly refactored `NodeManager` and `NodeGraph`, this will be useful for debugging purposes

### Additional context

* https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/195

See the wiki CLI and we need to update and iterate this.

Have @emmacasolin make sure that her article matches what this implementation is capable of.

### Tasks

1. Integrate DB into `IdentityManager`
2. Connect the `discovery/Discovery.ts` domain to the Identities CLI MR and `pk identities ...` subcommands, specify and add acceptance tests for these
3. Connect the `nodes/NodeGraph.ts` and `nodes/NodeManager.ts` to the Nodes CLI MR and specify the `pk nodes ...` subcommands.
4. Update all the `src/bin` commands

**Comment by CMCDragonkai** [comment]
For establishing a cryptolink between Node A and Node B, there needs to be an exchange protocol for cross-signing each claim. So the cryptolink claim is signed by both Node A and Node B and stored on the sigchain on both Node A and Node B.

This exchange protocol will eventually have to make use of the notification system: #192.

The development of this exchange protocol will need to be specced out and worked on in a separate issue. It will require both this issue and #192 to be finished.

**Comment by CMCDragonkai** [comment]
Seems like all the kinks we've worked out, so we expect this to be ready on Monday.

**Comment by CMCDragonkai** [comment]
@tegefaulkes make sure to use the prompt library.

**Comment by CMCDragonkai** [comment]
Are we on track for EOD Monday merge. After this is done and also #207, then we can focus on getting Node CLI up and running with ACL integration.

**Comment by joshuakarp** [comment]
!195 has now been merged in. I'll be writing a changelog + creating extra issues from the comments on the MR. Will the changelog + links to issues here.
