### ISSUE TITLE
Create automated tests for discoverGestalt

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#214]
### Specification

The `discovery` domain does not currently have automated tests. These are going to be quite heavyweight, integration tests that use various domains (`nodes`, `identities`, `gestalts`) to gradually build a local gestalt graph.

### Additional context

* comments regarding gestalt discovery can be found on !195 https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/195

**Comment by CMCDragonkai** [comment]
Status of this @joshuakarp ?

**Comment by joshuakarp** [comment]
Similar to fixing the gestalt graph test, I didn't look at this last sprint. Now that we're using `PolykeyAgent` instances in the tests though, I imagine this shouldn't be too difficult. Can also find a time to do this in this sprint.

**Comment by tegefaulkes** [comment]
Do you think we should group all test fixes and optimisations inside an epic?

**Comment by tegefaulkes** [comment]
Test has been completed for discovery via nodeId and identity.
Tests could be expanded with multiple gestalt configurations, needs looking into.

**Comment by tegefaulkes** [comment]
This has been merged in, resolving issue.
