### ISSUE TITLE
Fix automated tests for GestaltGraph

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#215]
### Describe the bug
The automated tests for `GestaltGraph` are currently broken as a result of the changes to types in !195. These tests simply need to be ported over to using the new types.

### Additional context

* type changes can be found in !195
* a changelog can be found here https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/184#note_631792744

**Comment by CMCDragonkai** [comment]
Status of this @joshuakarp ?

**Comment by joshuakarp** [comment]
@CMCDragonkai had a very brief re-look at this at the end of last week, but no progress made as of yet. I imagine it shouldn't take any more than a couple of hours, so can fit in sometime this sprint.

**Comment by CMCDragonkai** [comment]
Yea this will be important of course.

**Comment by joshuakarp** [comment]
This is fixed in !202: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/202/diffs?commit_id=52430403d56a7aaf2319abf72d77e55c85eedfcb

This issue can be closed once !202 is merged.
