### ISSUE TITLE
Extend automated tests for NodeConnection

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#216]
### Specification

Some extra functionality has been brought into `NodeConnection` from !195. Tests need to be added for them.

### Tasks

Add tests for:
1. `getRootCertChain`/`getExpectedPublicKey`
2. `getChainData`

**Comment by joshuakarp** [comment]
Given the refactoring that will be undertaken in #225, this will be part of that issue.

**Comment by joshuakarp** [comment]
The testing required from this issue will likely change as a result of the refactoring in #225. The aim is for `NodeConnection` to be quite a lightweight class, without a lot of redundant and repeated implementation details (most of this should be found and testing in `GRPCClientAgent`). Therefore, will need to readdress this after the refactoring in #225.

**Comment by CMCDragonkai** [comment]
What additional automated tests were done for this? @tegefaulkes @joshuakarp. Please elaborate based on #310.

**Comment by tegefaulkes** [comment]
This was just covered by the general test updates when working in #310, tests for the functions listed in the description above were added as well as any other missing tests. I can add some more details if you want.
