### ISSUE TITLE
GRPC call metadata is being overwritten when called from the Polykey GUI

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#221]
### Describe the bug

Call metadata is being overwritten when called from the GUI. It seems that the metadata is being overwritten somewhere along the GRPC. We have confirmed that the same happens for the token metadata when doing any GRPC call.

### To Reproduce

This applies to all calls but for the example i'll use the unlock session.

We are attempting to start a sesssion using the `sessionRequestJWT` GRPC call. it is called with an `EmptyMessage` and `Metadata` that contains the password.

```ts
const meta = new grpc.Metadata();  
meta.set('password', 'password');  
const emptyMessage = new clientPB.EmptyMessage();  
console.log('meta', meta);
const res = await grpcClient.sessionRequestJWT(emptyMessage, meta);
console.log(res.getToken());
```

We can confirm the metadata from the console.
```
meta Metadata {  
 internalRepr: Map(1) { 'password' => [ 'password' ] },  
 options: {}  
}
```

However on the agent side we receive
```
Meta:  Metadata {  
 internalRepr: Map(1) { 'user-agent' => [ 'grpc-node-js/1.3.6' ] },  
 options: {}  
}
```

### Expected behavior

We expect the metadata to be correct when received by `src/client/rpcSession.ts:18`
We expect it to look like;
```
meta Metadata {  
 internalRepr: Map(1) { 'password' => [ 'password' ] },  
 options: {}  
}
```

### Additional context

This problem only happens when run inside the GUI. 
The tests for sessions inside js-polykey still work.

### Notify maintainers
@DrFacepalm 
@CMCDragonkai

**Comment by tegefaulkes** [comment]
The commits with this problem can be found at.
- js-polykey 0e3b1294f80d45a6914e0b3163d9bd692dc322b3
- Gitlab Polykey-Desktop 809ef3a57b2b94ab09db8776a204608cb5631793

**Comment by tegefaulkes** [comment]
I've done some testing with both TypeScript-Demo-Lib and TypeScript-Demo-Electron. 
The problem seems to be with importing js-polykey and trying to use the GRPC from that.

I'll keep looking.

**Comment by tegefaulkes** [comment]
I've found the problem, both js-polykey and Polykey were importing `@grpc/grpc-js`. This seemed to work fine except for the fact the the metadata was missing on the server side. 

I've fixed this now by:
- removing the `@grpc/grpc-js` package from Polykey.
- created a `createMetadata` function inside `src/client/utils.ts:78` so we can create metadata without importing grpc directly.

**Comment by tegefaulkes** [comment]
I'm closing this as the issue is resolved now.

**Comment by CMCDragonkai** [comment]
What does this function|`createMetadata` do?||
|

**Comment by tegefaulkes** [comment]
I just creates and returns a grpc.Metadata() so I don't have to explicitly import grpc when I just need to create some metadata.

**Comment by tegefaulkes** [comment]
Reopening this issue to tests other methods of solving this problem.
- [ ] Explore other methods of importing.

**Comment by tegefaulkes** [comment]
Doing a quick test with the metadata again.
I wrote a small test program. the core of it is here;
```ts
    const echoMessage = new clientPB.EchoMessage();
    echoMessage.setChallenge('Hello!');
    console.log('First metadata');
    const meta = new grpc.Metadata();
    meta.add('First', 'Test');
    await grpcClient.echo(echoMessage, meta);

    //with other metadata.
    console.log('Second metadata')
    const meta2 = createMetadata();
    meta2.add('Second', 'Test');
    await grpcClient.echo(echoMessage, meta2);
```
`createMetadata()` is just a util function inside of `js-polykey/src/client/utils.ts` that returns a new metadata object.
This is so we don't need to explicitly import `grpc` or even include it as a package to make use of the `js-polykey` library.
```ts
function createMetadata(): grpc.Metadata {
  return new grpc.Metadata();
}
```

The result we get is;
```ts
First metadata
Echo meta:  Metadata {
  internalRepr: Map(1) { 'user-agent' => [ 'grpc-node-js/1.3.6' ] },
  options: {}
}
Second metadata
Echo meta:  Metadata {
  internalRepr: Map(2) {
    'second' => [ 'Test' ],
    'user-agent' => [ 'grpc-node-js/1.3.6' ]
  },
  options: {}
}
```

As we can see, if we create the metadata object via the explicitly imported `@grpc/grpc-js` the metadata `meta.add('First', 'Test');` fails to carry through the GRPC call.

As far as I can tell this is because we are separately importing GRPC. I've confirmed this inside js-polykey and the typescript demo lib. Now the only reason we import `@grpc/grpc-js` is to create the metadata. if we use the utility function to create it then we don't even need to include  `@grpc/grpc-js` as a node dependency.

I will explore other ways of fixing this however.

**Comment by tegefaulkes** [comment]
Importing via;
- `import * as grpc from '@grpc/grpc-js'`
- `const grpc = require('@grpc/grpc-js');`
- `import { Metadata } from '@grpc/grpc-js';`

All fail to fix the problem. Looking at the source for Metadata, the class doesn't store anything besides the optional options and the internal map for storage. I'm not sure how or why using it from a separate import causes this issue.

I'll do a little more research into this, but I think at this point the current solution is fine.

**Comment by CMCDragonkai** [comment]
Ok If this is the case. You need to write a comment above the utility 
function explaining why it exists. You can also post up an upstream 
issue indicating this weird property on grpc-js.

**Comment by tegefaulkes** [comment]
Ok, do you have a preference for which MR I should include this change in? @CMCDragonkai

**Comment by CMCDragonkai** [comment]
Just go straight to client-refactoring.

**Comment by CMCDragonkai** [comment]
It should probably go to `gprc/utils.ts` instead too.

**Comment by tegefaulkes** [comment]
Created an upstream issue at https://github.com/grpc/grpc-node/issues/1881.

**Comment by tegefaulkes** [comment]
I've re-exported the Metadata inside `src/client/index` with `export { Metadata } from '@grpc/grpc-js';` so we can import it along side `clientPB`.
This keeps it all in one place.

Just a note, only projects that use js-polykey as a library need to use that import. so far that's just the GUI. The CLI doesn't have this problem.

Also, there are some errors on the `client-refactoring` branch. I'm certain the change works. but to verify it again right now i'd have to fix like 18 bugs in that branch.

We can move this to review and close it if you're happy @CMCDragonkai

**Comment by CMCDragonkai** [comment]
Ok proceed to fixing bugs then. Close this issue once merged into client-refactoring
