### ISSUE TITLE
Registering providers

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#227]
### Specification
We need to discuss and specify how providers are registered. 
- Will end users be able to register their own providers?
- Bundled providers need to be registered. (just github for now.)
- How do we handle the clientId for a provider?

### Additional context
@joshuakarp @BrianBotha you guys should have a chat about how get this working properly in another MR/issue to client-refactoring.
I'm going to add the client id to the src/config.ts you'll need to have that.
The registerProvider is worth a discussion since you need to register a provider before it can be utilised. Question is whether users are meant to register providers?
For our bundled providers, they should all be registered ahead of time.

```
/**
 * Polykey configuration
 */
const config = {
  version: '1.0.0', // keep this synchronized with package.json
  stateVersion: 1,
  providers: {
    "github.com": {
      clientId: "ca5c4c520da868387c52"
    }
  }
};
```

The `github.com` matches the `ProviderId`.

@BrianBotha please create new issue on GH.

### Tasks
- [x] Merge in https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/211

**Comment by tegefaulkes** [comment]
I've created the issue for now. Will be expanded later. @CMCDragonkai

**Comment by CMCDragonkai** [comment]
This will be needed for our release so I'm adding it into our current sprint.

**Comment by CMCDragonkai** [comment]
This will need a new MR too.

**Comment by tegefaulkes** [comment]
Created a MR at https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/211

**Comment by CMCDragonkai** [comment]
Don't worry about users being able to register their own provider. We are only going to register our providers upon program startup.

**Comment by tegefaulkes** [comment]
Ok, I'll focus on just having our provided providers registered for now. We will need split users registering their own providers out as a separate issue.

**Comment by CMCDragonkai** [comment]
This issue can be closed as soon as you merge the MR. A separate issue can be created for registering their own providers. That's a plugin issue which is way later after release.

**Comment by tegefaulkes** [comment]
https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/211 has been merged.
Closing issue.
