### ISSUE TITLE
CLI app architecture 

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#23]
I'm thinking of using the following libraries in building the CLI app:

For building the core of the CLI:
https://www.npmjs.com/package/oclif

For text styling:
https://www.npmjs.com/package/chalk

For text output and formatting:
https://www.npmjs.com/package/winston

There were some other contenders such as [commander](https://www.npmjs.com/package/commander) and [yargs](https://www.npmjs.com/package/yargs), both of which have a much larger user base than oclif, which I'm mainly putting down to having mature codebase. 

The reasons I decided to go with oclif are: 

1. It's modern
2. Built by Heruko (Heruko CLI uses oclif)
3. Coded in typscript so it will integrate well with our codebase
4. Good multi/sub-command support
5. Clean api and good docs

**Comment by MeanMangosteen** [comment]
After spending some time on this matter, it seems commander and yargs both are argument parsers first, which you can build a CLI app on top of, while oclif is designed for building CLI apps at it forefront.

**Comment by robert-cronin** [comment]
It was decided to go with commander

**Comment by robert-cronin** [comment]
who knew `ctl+shift+enter` closed the issue, oops.
Like I said above, we have chosen to go with [commander](https://github.com/tj/commander.js/) due to its modularity and popularity. This issue will be closed by an upcoming PR that introduces a foundational CLI for existing methods.
