### ISSUE TITLE
Add extra testing for nodes claims process

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#242]
### Specification

Currently, there only exists a success test (for both client-side and server-side) and a couple of exception tests (for the server-side, in `GRPCClientAgent.test.ts`). Ideally, this should be extended for all possible exceptions on the server-side, and any other potential problems that can arise during this process. (This was originally omitted due to time constraints - it's slightly tedious and time-consuming to write these larger scale tests.)

Furthermore, it would be worthwhile to further investigate the possibility of mocking the server-side such that we can introduce more granular testing of the client side process. 

### Additional context

* original thread regarding mocking the server (good overall information) https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/209#note_673041297
* the original nodes claims MR https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/209
* original nodes claims issue #213
* #243 - Adding in deadlines to the nodes claim process

### Tasks

1. Create jest tests for each possible exception in the claims process. This can currently only be done for the server-side (by mocking the client) within `GRPCClientAgent.test.ts`
2. Investigate the possibility of mocking the server to produce granular testing for the client-side process (within `NodeManager.test.ts`/`NodeConnection.test.ts`)

**Comment by CMCDragonkai** [comment]
Any testing of node claim testing should make use of timer mocking as discussed in #274, #264, #243.

**Comment by joshuakarp** [comment]
This is a low priority task for the nodes refactoring process. We already have two basic, happy-path tests for both sides of the nodes claims process. This issue is merely about extending these to include the unhappy paths, and extend the server-side mocking (if possible).

**Comment by CMCDragonkai** [comment]
Not relevant anymore, will need to create a new issue if we see some problems.
