### ISSUE TITLE
Fix failing session test: parallel refreshing of sesion token

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#256]
### Describe the bug

The `Check parallel token refreshing` test is failing after the changes from the session token MR !212 were rebased into the vaults refactoring MR !205. The test was passing in !212 before merging, so there's potentially some conflict occurring in !205 causing the test failure.

### To Reproduce

1. `npm test -- tests/bin/sessions.test.ts`

### Additional context

* discussion of test failure https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/205#note_699811014
* original !212 MR https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/212 and test passing https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/212#note_698480173

### Notify maintainers

@emmacasolin

**Comment by joshuakarp** [comment]
This test may potentially just be disabled.

**Comment by emmacasolin** [comment]
After rebasing the retry loop branch on top of master I'm not seeing this failure - I think this means whatever was causing the test to fail in `vaults-refactoring` has now been resolved so this issue can probably be closed now.

**Comment by joshuakarp** [comment]
That's great - have also verified this in master:

```
[nix-shell:~/Documents/MatrixAI/js-polykey]$ npm test -- tests/bin/sessions.test.ts 

> @matrixai/polykey@1.0.0 test /home/josh/Documents/MatrixAI/js-polykey
> jest "tests/bin/sessions.test.ts"

Determining test suites to run...
GLOBAL SETUP
Process 1
Process 2
 PASS  tests/bin/sessions.test.ts (7.975 s)
  Session Token Refreshing
    ✓ Process should refresh the session token (30 ms)
    ✓ Serial processes should refresh the session token (57 ms)
    ✓ Failing processes should unlock the session file (20 ms)
    ✎ todo Process should store session token in session file
    Parallel processes should not refresh the session token
      ✓ Do process 1 (48 ms)
      ✓ Do process 2
      ✓ Check parallel token refreshing

Test Suites: 1 passed, 1 total
Tests:       1 todo, 6 passed, 7 total
Snapshots:   0 total
Time:        8.018 s, estimated 11 s
Ran all test suites matching /tests\/bin\/sessions.test.ts/i.
GLOBAL TEARDOWN

```

Closing this issue, as the test will be re-enabled in https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213#note_715070807.

**Comment by CMCDragonkai** [comment]
Should the tests still be rewritten to use Promise.all instead?

On 27 October 2021 11:03:47 am AEDT, Josh ***@***.***> wrote:
>That's great - have also verified this in master:
>
>
>
>```
>
>[nix-shell:~/Documents/MatrixAI/js-polykey]$ npm test -- tests/bin/sessions.test.ts >
>
>
>> @***@***.*** test /home/josh/Documents/MatrixAI/js-polykey
>
>> jest "tests/bin/sessions.test.ts"
>
>
>
>Determining test suites to run...
>
>GLOBAL SETUP
>
>Process 1
>
>Process 2
>
> PASS  tests/bin/sessions.test.ts (7.975 s)
>
>  Session Token Refreshing
>
>    ✓ Process should refresh the session token (30 ms)
>
>    ✓ Serial processes should refresh the session token (57 ms)
>
>    ✓ Failing processes should unlock the session file (20 ms)
>
>    ✎ todo Process should store session token in session file
>
>    Parallel processes should not refresh the session token
>
>      ✓ Do process 1 (48 ms)
>
>      ✓ Do process 2
>
>      ✓ Check parallel token refreshing
>
>
>
>Test Suites: 1 passed, 1 total
>
>Tests:       1 todo, 6 passed, 7 total
>
>Snapshots:   0 total
>
>Time:        8.018 s, estimated 11 s
>
>Ran all test suites matching /tests\/bin\/sessions.test.ts/i.
>
>GLOBAL TEARDOWN
>
>
>
>```
>
>
>
>Closing this issue, as the test will be re-enabled in https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213#note_715070807.
>
>
>
>-- >
>You are receiving this because you are subscribed to this thread.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/MatrixAI/js-polykey/issues/256#issuecomment-952422993
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
Not sure if I'm keen to fiddle with it now that it's working... what would be the benefits of switching to using Promise.all?

**Comment by CMCDragonkai** [comment]
Mainly cause the `test.concurrent` is considered experimental and 
not-documented. Seems like it has some problems with beforeAll/beforeEach.

**Comment by emmacasolin** [comment]
Ok, I'll have a look into changing it then. At the moment I'm getting around those issues by awaiting promises I've created to await setup in beforeAll/Each. Since everything else in https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213 is done the other tests can all be run while I'm rewriting `bin/sessions.test.ts`

**Comment by emmacasolin** [comment]
I've re-written those tests to use `Promise.all` and they're still passing. Definitely a lot cleaner this way too.

**Comment by CMCDragonkai** [comment]
This is still a problem now, but I think it needs to be reworked significantly. Need to discuss bin testing with everybody.
