### ISSUE TITLE
Integrate autoindexing into the `vaults` domain

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#257]
### Specification

Once autoindexing has been implemented into `js-db`, this should be brought into `js-polykey` and integrated into the `vaults` domain. 

### Additional context

* autoindexing issue in `js-db` https://github.com/MatrixAI/js-db/issues/1 and the corresponding PR https://github.com/MatrixAI/js-db/pull/2
* usage of the vault name for creation of a vault https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/205#note_700936060 and when enforcing uniqueness on creation https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/205#note_692109270

### Tasks

Provide support for:
1. Using the index to look up by vault name (currently, it performs a linear search over all vaults)
2. Using the index to look up by node ID from the `remote` field (i.e. a cloned vault that originally came from the specified node ID) - this would mean the node ID needs to be part of the metadata
3. Using the index to enforce the uniqueness constraint on vault name and to prevent duplicate vault names

**Comment by CMCDragonkai** [comment]
We're not going to do autoindexing anymore. See reasons in https://github.com/MatrixAI/js-db/issues/1
