### ISSUE TITLE
Crypto - Sign/Verify Commands

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#27]
Signing and verification is competing in the digital signature market. I think this may become a bigger issue in the future especially for non-repudiation.

But we need to make this easy for people to use. So I propose these commands:

```
# sign with the keynode's private key
polykey crypto sign ./file

# sign with some other private key that exists
polykey cyrpto sign ./file private-key-id
```

The private-key-id can be any thing that can uniquely identify the private key. So we may potentially store private keys in polykey as a secret and use these as well, but also maybe we have some totally different private key.

The signature produced should be a "detached signature". See gpg detached signature functionality: https://www.gnupg.org/gph/en/manual/x135.html

I think this default is the most obvious and flexible, we end up with a separate file as the signature. And verification would refer to both the original file and the signature. If the file was tampered with then the verification would fail.

```
# the signature should be able to identify what public-key we need to use
polykey crypto verify ./file ./file.sig
# alternatively we use this in order to specify the public key we need
polykey crypto verify ./file ./file.sig public-key-id
```

Also note that without further specification, the output is then the outputted signature or other notes. STDOUT should be used for the obvious output. STDERR for any reporting. STDIN for taking in passwords or other prompts.

**Comment by robert-cronin** [comment]
Sign/Verify commands were implemented in PR #35.
