### ISSUE TITLE
Creating `.proto` definition subdomains.

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#279]
### Specification
We need to update the protobuf definitions to split up messages for each domain into its own domain `.proto` file. we can use package names and imports to achieve this.

### Additional context
Relates to #249 

### Tasks
* [x] Prototype by abstracting into subdirectories under src/proto/schemas, and integrate google's protobuf library by first referencing it and then just copying verbatim
* [x] Create common domain types and common message types and share between Client.proto and Agent.proto

**Comment by CMCDragonkai** [comment]
Remember to assign yourself here and put it in right column too.

Also I think tick boxes for issues should only relate to the issue, other items go to the PR.

**Comment by CMCDragonkai** [comment]
Also I noticed this issue didn't have the labels automatically applied. Did you create the issue on github?

**Comment by tegefaulkes** [comment]
I think I created it from a task list in the related issue.

**Comment by CMCDragonkai** [comment]
Yea if aren't directly creating issues, make sure to add the appropriate labels and metadata.
