### ISSUE TITLE
Crypto - Keypair Creation

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#28]
It should be possible to create new key pairs. This can be used by other programs for whatever reason, or Polykey may change the master key of the keynode, but this may also involve re-encryption of any symmetric vault keys being used.

This is a low priority feature. Since many other programs usually allow creation of new keypairs to mean new digital identities. But in Polykey we don't really need to do that, since keynodes do not represent a new digital identity representing a person, but a unique agent that participates a in a P2P network.

But it can look like:

```
polykey crypto gen-keypair ./key ./key.pub
polykey crypto gen-keypair ./key
```

**Comment by robert-cronin** [comment]
This is available in the latest PR #40. Now one can call `generateKeyPair` and have it either replace the primary identity or just have it generate a new key pair for use else where.
