### ISSUE TITLE
Refactor `getConnectionToNode` to use the correct `ObjectMap` structure

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#282]
### Specification

Based on our sprint meeting today, the `NodeConnectionMap` and `getConnectionToNode` function in `NodeManager` needs to be refactored to match the `ObjectMap` pattern outlined by Roger.

Additionally, the [generic `ObjectMap` diagram](http://www.plantuml.com/plantuml/uml/VL11JiCm4Bpd5NDC3oXtAa4Hue04GkeFGZ9H3AuTrckL_XxNYL6WY9DtPsTclRCBseh6WwroKGadjbe1Pa3zu5HEC0ulhs_izBcTC7XPkiV-TWCTwL2V63OLC8ls33vAH_3J10rdESy-bspWwgPfX1h5GHPPqsoNOL0_vP8s4BNpHNKSZKt0a-_UOGA4bcrW-axgrZowFbFBoXaoG_NRylfUs2fXa-Fs1yAB1FBuQ7HSi--wZsZaBuDoLY7s_JS4zRD_7grtBEJzV5Xn_IUlabOvS9UUUB1V) should also be updated to reflect the usage of this pattern:

![image](https://user-images.githubusercontent.com/49772421/139617602-98c55deb-8945-4c6c-939b-12f810b3a9b5.png)

There's a possibility to look into whether we can generalise the `ObjectMap` into Polykey, such that we don't have the repeated `VaultMap` and `NodeConnectionMap` using the same pattern, but this is low priority. 

### Additional context

* gist with `ObjectMap` pattern https://gist.github.com/CMCDragonkai/f58f08e7eaab0430ed4467ca35527a42
* original diagramming issue https://github.com/MatrixAI/js-polykey/issues/258 `ObjectMap` diagram currently found on the following wiki pages:
   - [Vault Lifecycle](https://github.com/MatrixAI/js-polykey/wiki/vault-lifecycle)
   - [Node Connections](https://github.com/MatrixAI/js-polykey/wiki/Node-Connections)

### Tasks

1. Refactor `getConnectionToNode`
2. Change diagram

**Comment by CMCDragonkai** [comment]
I reckon the `getObject` function can be copy pasted right now and changed accordingly, or if you want, you can turn it into a higher order function and then acquire it. But there's only 2 places we're doing this right now so I think it's sufficient to copy paste. The diagram should then become linear with no loop involved. They all terminate at `createObject`.

Also consider changing the names to `resource` or be consistent with `object`.

**Comment by CMCDragonkai** [comment]
And remember objects in JS are mutable references!

**Comment by joshuakarp** [comment]
Diagram draft updated here https://github.com/MatrixAI/js-polykey/issues/258#issuecomment-955950837
