### ISSUE TITLE
Crypto - Encrypt/Decrypt Commands

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#29]
We should have the ability to encrypt symmetrically or asymmetrically.

To do asymmetric, we need to have a "trust database". Technically we could point to any known public key. But by default we would have to be able to choose among any possible known public keys. To make this easier, a short truncated code that locates the public key is possible too. So there may be multiple ways to locate a public key to use for asymmetric encryption.

```
# encrypts a file and asks for password (this is symmetric)
polykey crypto encrypt ./file
polykey crypto encrypt --password=./pass ./file
```

```
# encrypts file with id locating a public key
polykey crypto encrypt ./file public-key-id
```

```
# maybe something like this for multi-key encryption, this would be the case where multiple readers can read the same file 
polykey crypto encrypt ./file public-key-id public-key-id
```

Note that we prompt the user for secrets, as secrets should not be specified as plaintext arguments/options. However they can be passed in via options.

**Comment by robert-cronin** [comment]
Encrypt/Decrypt commands were implemented in PR #35.
