### ISSUE TITLE
1.0.0 Feature Freeze

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#291]
After the testnet deployment, the next stage of development with Polykey should be focusing on tying up the loose ends, such that we can perform our initial release!

We shouldn't be focusing on introducing new features (hence, "feature freeze"), and instead be looking at making the current state of Polykey as robust as possible.

Using this epic primarily as a means of categorising issues that should be a part of this enhancement process.

Template and description TBD

**Comment by CMCDragonkai** [comment]
Should this https://github.com/MatrixAI/js-polykey/issues/268 be before or after this gets done? I reckon we should release for test usage, and use this epic to organise everything that needs to be done for a 1.0 release.

**Comment by joshuakarp** [comment]
> I reckon we should release for test usage, and use this epic to organise everything that needs to be done for a 1.0 release.

This seems reasonable to me. I'd actually forgotten that we had #268. In that case, perhaps these should all be moved to #268? I was moreso treating this epic as just an interim container for all of the issues that I view as being important to finish up before an initial release, so this can be organised in another way if preferred..

**Comment by CMCDragonkai** [comment]
I think this issue can be made into a release version issue. Like `Release 11.0` or something. That makes it a feature freeze, and then work out all the final problems/optmisations/bugfixing/code quality issues.

**Comment by CMCDragonkai** [comment]
Some KeyManager quick fixes:

1. Don't need to read from the file when you are always just changing the keys, as it is expected nobody else can swap them around, use the in-memory key which should only be `this._dbKey`
2. Should be using locks to lock the operations on the key renewal, right now race conditions can occur in the side effects there.
3. Proper documentation on where subkeys are supposed to be located and managed by who like vault key, db key and session manager key.

**Comment by CMCDragonkai** [comment]
The error in:

```
class ErrorClientInvalidNode extends ErrorClient {
  exitCode: number = 70;
}
```

requires a proper review. It seems weird. Should this really be in `client/errors.ts`?

**Comment by CMCDragonkai** [comment]
I noticed that some exceptions are `Missing` and some are `NotFound`. So far no `Required`.

We should standardise on which suffix we use to mean these things.

**Comment by CMCDragonkai** [comment]
All uses of `fail` should be replaced with expectations. Details here: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213#note_742208447

**Comment by CMCDragonkai** [comment]
Should replace all use of `poll` in our `tests/utils.ts` with `src/utils.ts`. Any timeout usage should be done with `timerStart` and `timerStop`.

**Comment by joshuakarp** [comment]
Some very rough time estimates for the current state of this epic. Time estimates include planning, research, development, review and testing times:
* #261 + #254 (would be done concurrently): 3 days
* #159: should be done as part of testnet deployment (have removed from this issue for that reason)
* #264: 5 days
* #238: will be completed by #283
* #277: 2 days (should only require some benchmarking, and potential adjustments)
* #274: 1 day
* #244: 2 days
* #249: a fair bit more to consider here, so I'd overestimate at 7-10 days

**Comment by CMCDragonkai** [comment]
Mostly all done. We're going to do a testnet deployment in a couple days. Closing this.
