### ISSUE TITLE
Adding and maintaining own Gestalt in Gestalt Graph

### ISSUE THREAD

**Issue by emmacasolin** [MatrixAI/Polykey#319]
### Specification
Currently, the gestalt graph does not contain your own gestalt, however, this incorrect. We need a proper review of the Gestalt Graph theory and implement the expected behaviour.

### Additional context
- Discovered in https://github.com/MatrixAI/js-polykey/issues/316 and fleshed out discussion of expected requirements
- Original discussion of gestalt graph https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/144#note_501361799
- Issue for testing communication when the keypair changes - this would be relevant for the gestalt graph too https://github.com/MatrixAI/js-polykey/issues/317
- Original Gestalt Graphs MR https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/144
- Original discovery issue https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/issues/136
- GUI perspective of gestalt graph usage https://gitlab.com/MatrixAI/Engineering/Polykey/polykey-design/-/issues/31
- Updated Gestalt Discovery MR: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/195
- Gossip protocal for sharing the gestalt graph https://github.com/MatrixAI/js-polykey/issues/190

### Tasks
1. Full review of Gestalt Graph theory and gestalt trust
1. Add bootstrapped node to gestalt graph during bootstrapping
2. Incorporate Gestalt Graph into Node and Identity claiming process (including revoked/expired/invalid claims)

**Comment by CMCDragonkai** [comment]
This is now done by #446. The identities domain and nodes domain both manage the own gestalt graph. The discovery does not manage this.

The only thing missing is that the GG should have `setNode` called at the beginning of PolykeyAgent startup so that way the `GG` always has its own node there as a vertex. This should be done in #446 too.

**Comment by CMCDragonkai** [comment]
At the same time, the Discovery should be starting off from the GG but to do this we will need to introduce push-based dataflow to get the Discovery to react to changes in GG.
