### ISSUE TITLE
Problem with `tests/bin/keys/reset.test.ts` and `tests/bin/keys/renew.test.ts` stopping the PolykeyAgent

### ISSUE THREAD

**Issue by emmacasolin** [MatrixAI/Polykey#347]
### Describe the bug
When `tests/bin/keys/reset.test.ts` and `tests/bin/keys/renew.test.ts` use the shared global agent to run their tests (as opposed to their own separate agents) and are run at the same time, after the first test has finished running it will sometimes shut down the global agent even though there are still other processes using it. It will do this only if the other test is reading from the global data directory at the same time as when the first test is attempting to stop:
```
INFO:KeyManager:Reading /tmp/polykey-test-global-6W6c7T/agent/state/keys/db.key
INFO:KeyManager:Reading /tmp/polykey-test-global-6W6c7T/agent/state/keys/vault.key
INFO:renew test:Stopping PolykeyAgent
```

### To Reproduce
1. Checkout https://github.com/MatrixAI/js-polykey/pull/311/commits/dc53883c951b8a2b1e1978897856509b5962fea3
2. Run `npm test -- ./tests/bin/keys/reset.test.ts ./tests/bin/keys/renew.test.ts` (note that putting `renew` before `reset` seems to not reproduce the same issue)

### Expected behavior
The `Stopping PolykeyAgent` message can only come from the `PolykeyAgent.stop` method, however, this is not being called from inside `globalAgentClose`, as would be expected. We need to trace where this is being called from as it should only be called from `globalAgentClose` when using the global agent, which should only happen after all tests have finished running.

### Additional context
- https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1043952073
- https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1046449996

**Comment by CMCDragonkai** [comment]
This was worked around first by making these tests that use `renew` and `reset` use their own agent and not the global agent.

**Comment by CMCDragonkai** [comment]
Might be related to #386.

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you incorporate this since you've been removing the global agent. If we are removing the global agent, perhaps this issue can be resolved?

**Comment by CMCDragonkai** [comment]
Connect this issue to #404 if it is relevant.

**Comment by CMCDragonkai** [comment]
For these 2 tests, it was already swapped to using per-module agent.

Now with #404, these 2 tests are swapping from per-test-module agent to using global keypair.

Once it is using the global keypair fixtures, the per-test-module agent is now becoming a per-test-function agent. This means there no longer any state sharing of the agent across test functions.

So this issue will be closed once it is merged, but we should be wary if there's something broken in the key reset and key renew in the future.
