### ISSUE TITLE
Align `VaultInternal` `with` context API functions with `NodeConnectionManager`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#356]
### Specification
When performing operations with a vault, expect to pass a callback that receives the vault. I would want to align the API between `NodeConnectionManager` and `VaultManager`. This requires further specification.

Refer to #335 

### Additional context
* Relates #335 
* Relates #266 

### Tasks

1. ...
2. ...
3. ...

**Comment by emmacasolin** [comment]
The description of #374 says it fixed this issue - can this be closed now? @tegefaulkes

**Comment by tegefaulkes** [comment]
I think so. If I recall the sub-issues from #374 didn't auto close. @CMCDragonkai manually closed them. I'm not sure if he missed this or had a reason to leave it open.

**Comment by CMCDragonkai** [comment]
No I don't think this is done yet. But @tegefaulkes can verify it.

**Comment by CMCDragonkai** [comment]
I'm closing this since this has not been well specified.
