### ISSUE TITLE
Integrate Conventional Commits into CI/CD and Local Linting

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#358]
Conventional commits can be used to help create a standard for commits, like how we have done so for issue and pull request templates. Since our SoT repo is now GitHub, and GitHub does not have push rules, this has to be done instead in the CI/CD level. This can be integrated into our existing CI/CD pipeline with https://commitlint.js.org/#/. It would be applied on non-master branches only, and so would need to pass before PRs are merged in. No need to check on master repo, and also merge commit messages may not fit the convention anyway.

### Tasks

- ~[ ] 1. Introduce commitlint to local `npm lint` or as a separate lint command~ - not applicable because this is about `git` and not JS
- [ ] 2. Integrate it into the CI/CD linting (possibly as a separate linting command)
- [ ] 3. Enforce the conventional commit policy!

@tegefaulkes

**Comment by tegefaulkes** [comment]
I think as you've mentioned we can implement this using the git hooks. There is a server side push hook that can reject a commits based on criteria. Given `Conventional Commits` is a standard I expect we can find a hook implementation online that solves this already. Looks like `commitLint` can be integrated into a git hook easily.

Ideally we don't want commits that don't match the convention to end up on the origin branches. But that will prevent any WIP/EOD commits which may be an issue. Having it as a CICD step gives us more freedom but I can see a lot of force pushing new commit messages as a result of that.

**Comment by CMCDragonkai** [comment]
It can be done by limiting it to the `staging` branch. So then feature commits can still be WIP commits, that just has to be squashed and rewritten. Of course, the issue is that some commits like `npm version` commits don't follow that standard, so that's an issue. I'm not sure.

And since this has nothing to do with JS, I realise that `npm lint` is not applicable here.

**Comment by CMCDragonkai** [comment]
I did have a look at this, and there is indeed a commit hook useful for this. The commit hooks can be placed in the git repository. https://stackoverflow.com/questions/427207/can-git-hook-scripts-be-managed-along-with-the-repository. Then one could run a program. However this is likely not portable, unless executed via npm using `commontlint.js.org`. However this is not portable to non-JS projects, so something that runs an external program is better, but this would rely on our `nix-shell` being available on Windows and MacOS. Since they are not first class development systems, I suggest that the hook should run if the program is available, and if it isn't, don't bother running it.

It doesn't actually make sense to put this in the CI/CD, unless it's added as a push rule. But I'm reluctant on enforcing this atm as it not all commits fit the standard. So I'm leaning towards just closing this issue as it's not that important and we have all started writing commit messages in this way.

Maybe in the future.
