### ISSUE TITLE
Adding timeout overrides to `NodeConnectionManager` methods

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#363]
### Specification
While we can specify the timeouts when creating a `NodeConnectionManager` there are cases where we want to be able to specify a timeout when creating a connection. 

For this we will need to add an optional `connConnectTime` parameter to any `NodeConnectionManager` method that can create a connection. this ill override the timeout of trying to create a connection if set.

### Additional context
- Relates #322 needs this to avoid blocking for a long time when checking a node.

### Tasks
1. Add optional timeouts to all of the `NodeConnectionManager` methods that could create a new connection.

**Comment by tegefaulkes** [comment]
Didn't really need an issue for this since it's a small change. But it leaves a paper trail for discussion. 

I'm in the process of adding the timeout to the methods such as  `createConnection`, `establishNodeConnection` , `withF` and `withG` being the main ones. Do we want to add optional timeouts for `getClosestGlobalNodes`, `getRemoteNodeClosestNodes`, `syncNodeGraph` etc?

@CMCDragonkai

**Comment by CMCDragonkai** [comment]
Some of those methods could an async generator right?

**Comment by tegefaulkes** [comment]
Yeah, withConnG is an async gen, the others are normal.

**Comment by tegefaulkes** [comment]
I'm going to update this to use timers instead of a timeout value. this way we can compose timeouts.

**Comment by tegefaulkes** [comment]
Fixed up the timeouts to use timers.

**Comment by emmacasolin** [comment]
The resolution of this issue should allow for https://github.com/MatrixAI/js-polykey/issues/353 to be easily completed since it will allow for a timeout to be set for the `NodeConnectionManager` methods called within the Discovery domain.
