### ISSUE TITLE
`pkg.js` fails to include `tslib` dependency

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#387]
### Specification

`pkg` is failing to properly include the `tslib` dependency. This is needed by `async-locks` and `cheerio` as a dependency. 

The problem seems to be that `pkg` is adding the `tslib` files to the queue during the walker phase but only as the bytecode. during the packing phase when it attempts to add the required files it skips them due to our use of the `--no-bytecode` flag. Thus throwing the following error.

```
> Error! --no-bytecode and no source breaks final executable
  /home/faulkes/matrixcode/polykey/js-polykey/node_modules/tslib/tslib.js
  Please run with "-d" and without "--no-bytecode" first, and make
  sure that debug log does not contain "was included as bytecode".
```

We suspect this may be due to pkg not properly parsing es6 modules. Discussion about this can be found starting from [here](https://github.com/MatrixAI/js-polykey/pull/379#issuecomment-1162647062)

Currently a stopgap fix is to force include `tslib` by adding the files as an asset to the pkg config in `package.json`.
```ts
  "pkg": {
    "assets": [
      "node_modules/tslib/**/*.js",
      ...
    ],
  },
``` 

### Additional context

- Related #379 
- Comments https://github.com/MatrixAI/js-polykey/pull/379#issuecomment-1162647062
- Problem package https://www.npmjs.com/package/tslib
- Related https://github.com/vercel/pkg/pull/1323

### Tasks

1. determine a better fix if any.
2. use a bundler to circumvent the problem.

**Comment by CMCDragonkai** [comment]
You've fixed this by adding `tslib` directly into the `pkg` configuration in #379. We're going to side-step this issue by solving the root of the problem in https://github.com/MatrixAI/Polykey-CLI/issues/23 by using a purpose-built bundler first, then using `pkg` only for the last step of combining it virtual filesystem for non-js assets, and native addons as well as the node executable.
