### ISSUE TITLE
Revocation of asymmetric master key and symmetric vault keys

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#39]
We need to start thinking about revocation. Particularly revocation of a vault key and how we would propagate it through a PolyKey network.

It will be less common to revoke the master key of a particular keynode and that keynode would become untrustworthy from that point on. This might happen if a user has many sub-keynodes and one of them becomes compromised.

**Comment by robert-cronin** [comment]
Revocation of vault key is a non-issue because it is never shared, the vaults are shared over a secure wire with transport layer security and then re-encrypted on the other end with that keynodes own derived sym key.

**Comment by CMCDragonkai** [comment]
I think this issue can be changed to be about key-rollover. As in rekeying a vault or the master key. This can be done interactively.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
