### ISSUE TITLE
Verify that pre-release and release jobs work

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#390]
### Specification

Verify that the release CI/CD job functions properly by pushing up a pre-release and release commit. If any problems arise then that needs to be fixed.

### Additional context

- related #379 

### Tasks

1. Push a pre-relase commit and verify it works.
2. Push a release commit and verify it works.
3. Fix any problems with the release CI/CD job if there are any.

**Comment by CMCDragonkai** [comment]
I can verify that the pushing of the container images are working properly. As for the publishing of the npm packages. Can't do that until we have all the tests passing without any intermittent failures.

**Comment by CMCDragonkai** [comment]
This appears to have been done via the merges in #379 and subsequent prerelease tags.

However a release tag isn't done yet, but we can assume it probably works the same as the prerelease tag.
