### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#400]
### Specification

IPv4 is being exhausted, and much of the new internet will be ipv6 only.

The PK agent should support binding, listening and connecting to IPv6 addresses.

Currently we're limited in several ways:

1. The `utp-native` has no IPv6 support
2. NAT busting hasn't been tested with IPv6 (what kind of NAT architectures would exist for IPv6)
3. DHT hasn't been tested with IPv6
4. CLI option parsing hasn't been tested with IPv6
5. Our AWS NLB which runs the testnet and mainnet does not yet support IPv6 with UDP protocol
6. AWS VPC/subnets hasn't been tested with IPv6 or configured with IPv6 assignments
7. Our GRPC server (and perhaps client service in general) hasn't been tested with dual stack assignments, supporting IPv6 means we should still listen on IPv4 at the same time (but this requires documentation of the options)

All of the above has to be solved to support IPv6.

### Additional context

* https://github.com/MatrixAI/js-polykey/issues/234 - replacing utp-native with quic would allow IPv6
* https://github.com/MatrixAI/js-polykey/issues/194 - notes on IPv6 work in AWS and the relevant PR https://github.com/MatrixAI/js-polykey/pull/396
* https://github.com/MatrixAI/js-polykey/issues/153 - IPv6 also has their own multicast domains
* https://stackoverflow.com/questions/47797322/node-js-server-only-listening-on-ipv6
* https://www.grouparoo.com/blog/node-js-and-ipv6

### Tasks

1. Add tests to Node Connection to test local IPv6 usage
2. Enable IPv6 on the testnet
3. Apply integration tests to the testnet infrastructure
4. IPv6 supported by quic layer.
5. IPv6 supported by websocket layer.
6. IPv6 discovery with MDNS.
7. IPv6 supported by nodeGraph.

**Comment by CMCDragonkai** [comment]
RPC is no longer limited to IPv4, it can do IPv4 or IPv6.

The question of IPv6 is actually more pertinent to QUIC or WebSockets, however I think these should work without any problems.

More testing is required for the `nodes` domain to ensure that IPv6 is working too.

We're no longer using any load balancer in AWS.

@tegefaulkes can add more details here.

**Comment by tegefaulkes** [comment]
The agnostic RPC doesn't care about transport so long as it's a bi-directional `UInt8Array`.  So yeah, the IPv6 support comes down to the websocket and quic implementations. I think both should be able to support it.

**Comment by CMCDragonkai** [comment]
Testing for IPv6 is relevant for agent migration.

**Comment by CMCDragonkai** [comment]
Isn't this part of the agent migration @tegefaulkes?

**Comment by tegefaulkes** [comment]
I can add it to #535 , Though I think IPv6 support is added by just using js-quic now. So it's something to check.

**Comment by tegefaulkes** [comment]
For this to be considered done, we'd need to support IPv6 on every level. We need to track the IPv6 address in the nodeGraph. Possibly as part of #537. The websocket transport layer needs to support it, I think it can so likely that's a simple change. Lastly we'd want to discover 'local' IPv6 addresses with the `MDNS` system.

**Comment by CMCDragonkai** [comment]
So one thing I'm doing is aligning up the network configuration since it's currently quite confusing.

```
      // Using `localhost` defaults to OS configuration
      agentHost: 'localhost',
      agentPort: 0,
      // Using `localhost` defaults to OS configuration
      clientHost: 'localhost',
      clientPort: 0,
      // If using dual stack `::`, this forces only IPv6
      ipv6Only: false,
```

So originally this was set to `127.0.0.1` because we only had IPv4 support.

Now with both websockets and QUIC supporting IPv6, we should default to dual stack right?

Now only `::` is dual stack. The other designations are not automatically dualstack. This is just how nodejs worked.

Now there's another problem. Polykey is by default a distributed and decentralised system.

I just checked the default values set on `Polykey-CLI` and this is set to whatever is the default network configuration.

That would mean when users launch PK, they launch only binding to localhost. That won't work at all!

Instead we need to understand that by default `agentHost` should be `::`, whereas by default `clientHost` should be `localhost`.

This provides secure defaults for the client service while also maintaining that the `agentHost` is supposed to be public.

Next the `ipv6Only` option should control both the client service and the agent service. And also note that it would only ever activate if `::` is the binding that is being used.

**Comment by CMCDragonkai** [comment]
Both js-quic and js-ws will be ipv6 native, in fact dual stack native!

**Comment by CMCDragonkai** [comment]
WS and QUIC are both integrated. We should test ipv6 support on PK CLI @tegefaulkes. I'm going to close this for now, because technically PK underlying code should fully support it, however node graph fixes may be required. Task 7 that is. We do it under #551.
