### ISSUE TITLE
Object map locks should be removed in favour of transaction locks

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#443]
### Specification

We should remove all the object map locks in favour of the transaction locks. This is because locks don't compose, and all the object maps are just representations of the source of truth on disk. Ideally we should use the `tran.queueSuccess` and such that can do in-memory changes only after a commit occurs. This means local state inside a transactional function is temporary, and only after a commit succeeds, does global (domain state) get mutated.

Generally I reckon we shouldn't have any operations that is mutating the in-memory state without also involving the underlying disk, so there shouldn't be a situation where they can't coordinate with the transaction locks.

The transaction locks are far more useful generally because they are re-entrant, and they don't release until transaction destruction.

_Originally posted by @CMCDragonkai in https://github.com/MatrixAI/Polykey/issues/419#issuecomment-1222133505_

### Additional context

* #419 - discovered issues with the vault map locks and the transaction locks, transaction locks are re-entrant, vault map locks are not, also vault map mutation can be done with the `queueFinally`.

### Tasks

1. Identify all object map lock usage
2. Prototype the change to using transaction locks with global domain state mutation done by `queueFinally`
3. Make the change, and test concurrent behaviour

**Comment by CMCDragonkai** [comment]
The #382 should be done first before this so we can have proper verification of our concurrent behaviour now.

Removing the object map locks means we should still verify whether our mutation doesn't have any race conditions during in-memory object creation.

**Comment by CMCDragonkai** [comment]
@tegefaulkes what object map locks do we still have?

1. Nodes?
2. Vaults?
3. Any where else?

**Comment by tegefaulkes** [comment]
I think those are the only two.

**Comment by CMCDragonkai** [comment]
The proxy had their object map locks replaced recently. So there were 3.

Nodes and vaults still has it.

@tegefaulkes can you also address the nodes change in your next PR.

**Comment by tegefaulkes** [comment]
The nodes domain object maps were already replaced with `LockBox`. So i think that's addressed.

**Comment by CMCDragonkai** [comment]
Great so only vaults left.

**Comment by CMCDragonkai** [comment]
So vaults domain is the only place where it's actually replacing object map locks with transaction locks. The other 2 are just using in-memory lockbox.

**Comment by CMCDragonkai** [comment]
@tegefaulkes is the vaults domain still using object map locks or has it been transitioned to `LockBox`?

If it has been transitioned, this should be closed.

**Comment by tegefaulkes** [comment]
I think vaults was updated with c2566202880e4f1801e870d65ebe7fcb03952048.

There may be an object map in the `Proxy` before that is removed fully in agent migration.

**Comment by CMCDragonkai** [comment]
Ok since that is to be removed, then this is closed.
