### ISSUE TITLE
Optimise `NodeConnectionManager.getClosestGlobalNodes` to concurrently contact nodes

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#448]
### Specification

`getClosestGlobalNodes` is the core logic for finding a node within the Kademlia network. Currently is implemented as a priority queue that queries a node for a list of nodes close to the target node. it then sequetially pings each node to see if it's alive before adding it to the `NodeGraph`. 

This needs to be optimised to ping K nodes concurrently. It also needs to only ping and contact nodes in the priority order.

### Additional context

- Related #445 
- Related https://github.com/MatrixAI/Polykey/pull/445#discussion_r974992579

### Tasks

- [ ] 1. Nodes need to be pinged concurrently to check if they're alive. We can use the `Semaphore` from `@matrixai/async-locks` to enforce the concurrency limit.
- [ ] 2. Only ping a node just before trying to connect to it. There is no need to ping every node since we only need to connect in the priority order.

**Comment by tegefaulkes** [comment]
This issue is not relevant anymore. The `findNode` procedure was completely revamped in #618 .

**Comment by CMCDragonkai** [comment]
So it is not sequential anymore?

**Comment by tegefaulkes** [comment]
Yep, up to 3-6* connections are made concurrently during the `nodesFind` operation depending on how it's configured. Nodes are added to the `NodeGraph` when the `NodeManager` handles the connection event.
