### ISSUE TITLE
Update `timedCancllable` decorator to support dynamic timeouts

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#463]
### Specification

The `timedCancellable` decorator needs to be updated to support dynamic timeouts. Currently it's limited to static values defined at 'import time'. This feature is needed to allow for custom defaults when creating the `NodeConnectionManager`.

The spec for this is defined within this comment. https://github.com/MatrixAI/Polykey/issues/450#issuecomment-1261634752

### Additional context

- Related https://github.com/MatrixAI/Polykey/issues/450#issuecomment-1261634752

### Tasks

1. Update the `timedCancellable` decorator to support values that can be set dynamically.

**Comment by tegefaulkes** [comment]
On trying this out. Using `(this: any) => boolean` as a type doesn't quite work. 

In `timedCancellable` if I get the value with `const lazy_ = typeof lazy === 'boolean' ? lazy : lazy.apply(this);` and then try to use the decorator.

```ts
// TS2730: An arrow function cannot have a 'this' parameter.
@timedCancellable(true, (this) => this.delay)

// TS2532: Object is possibly 'undefined'.
@timedCancellable(true, () => this.delay)

// TS2339: Property 'delay' does not exist on type 'never'.
@timedCancellable(true, () => this?.delay)
```

If I replace `this` with the name `object` in the arrow function then

```ts
// Inside the `timedCancellable`
const lazy_ = typeof lazy === 'boolean' ? lazy : lazy(this);

// this would work
@timedCancellable(true, (object) => object.delay)

```

**Comment by CMCDragonkai** [comment]
Oh was the `this` a reserved keyword? Yea. So `object` as the keyword is fine.

**Comment by CMCDragonkai** [comment]
I just remembered that the convention is to use `that`. But I think `self` makes more sense here.
