### ISSUE TITLE
Update `Discovery` domain to use `timedCancellable`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#477]
### Specification

The discovery domain has a long running process of connecting to other nodes. This needs to support cancellation. On review, there is only one method that needs cancellablility, that is the `processVertex` method. This is already used as a task handler so it already supports cancellablility. But to cap off this issue some small changes still need to be made.

Since `processVertex` is a compound task, it doesn't make sense to have a default timeout for it. The overall timeout of the method should be the result of the individual timeouts of the method calls within it. We still need to support an overall timeout for the whole process if we want it. this means we only pass the signal into sub calls and create new timers for each one based on the parameter.

Each downstream call that has it's own timeout needs to have it's timeout set as a parameter of the `processVertex()` method. The main one is the `nodeManager.requestChainData()` calls but there may be others that make connections to nodes. These still need to be updated with a context, I must've missed them in the nodes domain PR.

### Additional context

- Fixes #353
- Related #450 

### Tasks

1. Default the timeout for `processVertex` to infinity.
2. Add a parameter for override timeout for each sub-connection. Create a new timer for each connection and propagate the signal.
3. These connections need to take an optional `ctx` context, but we don't need to fully convert them to `timedCancellable` since only the `nodeConnectionManager.withConnF` makes use of the `ctx` and that's already a `timedCancellable`.

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you check how much of #462 is relevant to this issue? In the interests of time, we only want to ensure that don't wait 20 seconds for each discovery operation.

**Comment by tegefaulkes** [comment]
At first glance, This issue is reasonably separate from #462. All I have to do to complete this issue and #353 Is to go over the timedCancellable usage, update the cancellation logic and make sure that any 'child' connection created as part of the discovery loop has it's own timeout as per #353. 

#462 deals with a deeper refactor of the logic and appying new features such as the priority and TTL.
