### ISSUE TITLE
Provide `dbKey` to `DB` when starting

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#480]
### Specification

When the `KeyRing` is stopped, the `dbKey` is zeroed out due to unlocking the memory. This causes the `dbKey` inside of the `DB` to become invalid. Currently this is causing issues with `PolykeyAgent.destroy()` when the DB starts up to allow domains to clear data. It will also cause an error with stopping and starting the `PolykeyAgent`. 

A quick fix was applied where the `dbKey` was only unlocked and cleared when the `KeyRing` was destroyed. But a better fix for this would be for the `DB` to take the `dbKey` when starting instead of when creating. He we'll need to pass the `dbKey` to the db during starting. A new issue and fix needs to be made in the `DB` repositry to allow setting of the `dbkey` when starting the DB. Likewise the `EncryptedFileSystem` will need to be updated.

### Tasks

1. Update `@matrixai/db`to allow setting the `dbkey` when starting the DB.
2. Update the `encryptedfs` to make use of this change.
3. Update Polykey to make use of this change.
4. Revert the quickfix where we unlock the `dbKey` in `KeyRing.destroy()`.

**Comment by CMCDragonkai** [comment]
This is now done and will be merged in #446. But I'm closing this since this was meant to be in the js-db.
