### ISSUE TITLE
feat: handling many to many relationship between nodes and addresses

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#485]
### Requirements of this design

There is a possible many to many relationship between `nodeIds` and addresses. We need to add logic to the nodes system to handle theses cases. This issue is an epic to track this body of work.

The main changes boil down to two core parts.
1. The ability to resolve a hostname to multiple addresses and try each one when connecting to a node. This should allow us to connect to a specific node when using a generic domain name for the address. 
2. The ability to try a set of addresses when searching for one or more nodes out of a set of nodes. This is useful for network entry where we are looking for 3 seed nodes on the `testnet.polykey.io` domain. Here we have a set of expected and trusted seed nodes but we can end up talking to any of them on that domain.

### Additional context

* Related MatrixAI/Polykey-CLI#71
* Related reading https://github.com/MatrixAI/Polykey-CLI/issues/71

### Sub-Issues & Sub-PRs created

1. MatrixAI/Polykey#482
3. MatrixAI/Polykey#483
4. MatrixAI/Polykey#484

**Comment by CMCDragonkai** [comment]
What's the status of this epic @tegefaulkes?

**Comment by tegefaulkes** [comment]
I suppose MatrixAI/Polykey#482 still needs to be addressed but I don't think it's high priority or even needed right now. We may need to track the last known hostname, public IP and private IP of a node. The private IP would be needed to coordinate connecting to nodes on the same network but that's a feature for later.  

If we allow for multiple address records per nodeId then instead of overwriting the same record we end up adding new records. This could lead to this data bloating over time if we don't have a clean up policy. 

But like I said, I don't think MatrixAI/Polykey#482 is needed right now so it can be addressed when we need that functionality.

**Comment by CMCDragonkai** [comment]
We can close this for now, and leave MatrixAI/Polykey#482.
