### ISSUE TITLE
Master Key Encryption or Missing

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#49]
Upon creation of a Polykey keynode, we always generate a master key. Every keynode should have a unique master key as that represents its digital identity. This is because keynodes are participating in a P2P network, and so keynodes should have unique identities.

The user must be offered to encrypt the master key with a master password, or be given the master key, in which case the keynode state no longer keeps around the master key. This means the user must either supply the master password to decrypt the master key, or supply the master key for authentication.

**Comment by robert-cronin** [comment]
I'm actually thinking for vault keys, we shouldn't store them as the raw keys (I have the keys encrypted at the moment by the keyManager: #22. As was mentioned above, we could use `pbkdf2` based on the master private key and a salt and then just store the salt instead and re-derive the keys when needed, although this might add some time to startup.

**Comment by CMCDragonkai** [comment]
I imagined that the keys would be stored encrypted (as part of the EFS state), but you have to supply the key to decrypt it.

In Hashicorp vault, the root key encrypts little keys which decrypt the individual vaults. Same thing can happen in our case. Except the passphrase to efs is the little key.

So the question is that given the root key, there must be a way to acquire automatically the little keys for each vault.

Also since each vault should have a different little key, then we can ensure that we don't have all the vaults loaded into memory straight away, but instead are brought up when they are needed and then cached until some TTL.

Principle of least privilege, and bounded privilege pattern.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
