### ISSUE TITLE
fix: seed nodes crashing from ending connections

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#494]
### Specification

Due to recent changes the seed nodes have started crashing. The cause of the crash seems to be when a node connection to the seed node shuts down. So far I've seen it when running the `testnetConnection.test.ts` tests, the first run of the test succeeds and the 2nd tends to fail due to the seed node crashing. So far as I can tell, the clean up stage of the test where we kill the agent process with a `SIGINT` signal is when it happens. 

On the seed node side of things we see the following error.

```
{
    "type": "TypeError",
    "data": {
        "message": "Cannot read properties of null (reading 'finishShutdown')",
        "stack": "TypeError: Cannot read properties of null (reading 'finishShutdown')\n    at JSStreamSocket.finishShutdown (node:internal/js_stream_socket:160:12)\n    at Immediate.<anonymous> (node:internal/js_stream_socket:234:12)\n    at processImmediate (node:internal/timers:466:21)"
    }
}
```

A cursory search found this issue https://github.com/nodejs/node/issues/35695 which indicates this may be a bug in nodes HTTP implementation. Further investigation is needed.

### Additional context

- Related https://github.com/MatrixAI/Polykey/pull/474#issuecomment-1308087835

### Tasks

1. Find the core cause of the problem
2. fix the problem

**Comment by CMCDragonkai** [comment]
Need to review this as part of #551.

**Comment by tegefaulkes** [comment]
This Issue relates to the old test-net deployment and old network stack.

After converting to `js-quic` this is no longer relevant.
