### ISSUE TITLE
Redundant events in commit messages

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#5]
As of now, the logs of commit messages are formed with the granularity of filesystem level changes. That is, Polykey logs any events deemed a change of state according to the filesystem, e.g. creation, modification, removal of a file...

But consider the case where a file: `foo.txt` contains the text: 
```
bar
```
You can open this file and make no modifications and write the file again; or delete the entire contents, save it, and write `bar` again. The mtime of file will change and the filesystem will detect this as a change and as a result Polykey will also log this change despite the fact there is no change with respect to a secret's state.

So we need to look into log deltas based on secret/file granularity. Git maintains a cheksums for each file's contents in the working directory, staging area, and repository. It compares the checksums to determine if a file has been modified. Perhaps we can do something similar.

**Comment by CMCDragonkai** [comment]
I wonder if this is a problem we can solve at a higher level.

If there's no change that we can detect at the higher level, it's just a noop.

On the otherhand what's the harm in allowing this to happen?

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
