### ISSUE TITLE
Lockfiles to constrain keynodes to a single agent

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#51]
Also it is intended to have a single agent per user that can manage multiple keynodes just like a single ssh-agent per user can manage multiple keys. For any particular keynode, it can be registered against a particular agent that represents the authentication context for that keynode. 

To prevent multiple agents (i.e. muiltiple users on the same system) from managing the same keynode, we could create a lockfile that constrains the keynode to a particular running agent.

**Comment by robert-cronin** [comment]
This wasn't implemented in the linked PR so I'll be removed the `Fixes` keyword

**Comment by CMCDragonkai** [comment]
Lockfiles are not supported on VFS.

This is because lockfiles are platform specific, not agnostic.

And since this is about how the actual fs is stored, we would need to specialize this to the specific fs implementation. On Unix OS, we have flock. But what about windows?

**Comment by robert-cronin** [comment]
ahh yes we probably need an isomorphic implementation of something like [npm/lockfiles](https://github.com/npm/lockfile) although the [source file](https://github.com/npm/lockfile/blob/master/lockfile.js) doesn't look too complicated, we could probably adapt it to an `isomorphic-lockfiles`

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
