### ISSUE TITLE
Importing `@streamparser/json` results in error when using `tsc` or `jest` relying on `tsc`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#516]
### Specification

As part of #249 we're using a JSON stream parser to parse the JSONRPC messages. There seems to be a problem with this library specifically where we can't import it with the `import` keyword. So far a work around has been to import it with `const jsonStreamParsers = require('@streamparser/json');`. 

We need to import it with `import { JSONParser } from '@streamparser/json';`. but currently doing so results in a `TS2307: Cannot find module '@streamparser/json' or its corresponding type declarations.` error.

So far I haven't been able to determine why the usual import isn't working. From what I can tell it's using conditional exports within it's `package.json` file for specifying the exports. This may be related?

### Additional context

* Related #509 

### Tasks

1. determine the cause of the import error.
2. find a fix to import the stream parser using the `import` keyword.

**Comment by tegefaulkes** [comment]
Created an upstream issue at https://github.com/juanjoDiaz/streamparser-json/issues/25.

**Comment by CMCDragonkai** [comment]
This works fine in a prototyping script:

```ts
import { JSONParser } from '@streamparser/json';

async function main() {
  console.log(JSONParser);
}

main();
```

It's only the IDE that complains. Running `npm run ts-node -- ./test.ts` works.

```
> polykey@1.0.1-alpha.0 ts-node
> ts-node "./test.ts"

[class JSONParser]
```

**Comment by CMCDragonkai** [comment]
Are you getting that error when running JEST tests? If not, then ignore the IDE, and just proceed. It's just an IDE configuration issue.

**Comment by CMCDragonkai** [comment]
I see... it fails in jest, but works in `ts-node`.

**Comment by CMCDragonkai** [comment]
Note that our `ts-node` is in fact using `swc`, whereas `jest` is not currently using `swc`.

**Comment by CMCDragonkai** [comment]
I think this is related to: https://github.com/MatrixAI/TypeScript-Demo-Lib/issues/32. The package appears to be module type. But it must be breaking on resolution somehow.

**Comment by CMCDragonkai** [comment]
Here you can see the issue:

```
tsc ./test.ts
```

```
test.ts:1:28 - error TS2307: Cannot find module '@streamparser/json' or its corresponding type declarations.
```

But if I use swc it ends up keeping it as regular imports.

I think this is because our `tsconfig.json` specifies CommonJS modules. Perhaps upstream package isn't well tested with commonjs tsconfigs.

**Comment by CMCDragonkai** [comment]
This should be done with the merge of #513.
