### ISSUE TITLE
Replace `readable-stream` usage with Web Streams in the Vaults and Git Domains

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#523]
### Specification

Some parts of the code are still using `readable-stream`. these need to be replaced with webstreams and the `readable-stream` dependency removed from the `package.json`.

These usages can be found at 
```

[nix-shell:~/Projects/Polykey]$ ag "from 'readable"
src/vaults/VaultManager.ts
24:import { PassThrough } from 'readable-stream';

src/git/types.ts
1:import type { PassThrough } from 'readable-stream';

src/git/utils.ts
22:import { PassThrough } from 'readable-stream';
```

### Additional context

* https://github.com/MatrixAI/js-encryptedfs/issues/75 - Git related streams may have some relationship with EFS readable stream changes, can also fix that up too (however EFS will cannot use web streams, since it has to simulate node FS streams)

### Tasks

1. ~[ ] 1. Replace any `readable-stream` usage with `stream/web`.~ - replacing with async generator
2. [x] 2. Remove `readable-stream` as a dependency from the `package.json`.

**Comment by CMCDragonkai** [comment]
The readable-stream is also being used by EFS. That can't really be changed, it has to simulate node streams. However it's a really old readable stream. Might be better upgraded to match the latest stream behaviour. Not sure.

**Comment by CMCDragonkai** [comment]
I'm putting this under #298 because the usage of readable streams is relevant to git and EFS which is still using the old readable stream implementation in order to simulate how Node streams work, but Node streams have changed quite a bit since the initial import from VFS.

**Comment by CMCDragonkai** [comment]
Ok vaults domain should be using web streams, same with git. The git domain needs significant refactoring.

The EFS has to continue using "fs streams", it just requires an update to the fs stream backing library, and then testing to see that everything still works.

**Comment by CMCDragonkai** [comment]
Ok vaults domain should be using web streams, same with git. The git domain needs significant refactoring.

The EFS has to continue using "fs streams", it just requires an update to the fs stream backing library, and then testing to see that everything still works.

**Comment by tegefaulkes** [comment]
This might actually be addressed by the #709  PR, I'll double check and include this issue as fixed if so.

**Comment by CMCDragonkai** [comment]
Yes so if this is done, remove the dependency from package.json too. It will continue to be used by EFS until it can be refactored too.

**Comment by tegefaulkes** [comment]
I double checked and it's all gone. I've removed the dependency in #709 and made it fixed by that as well.
