### ISSUE TITLE
Update npm root paths for relevant repos

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#524]
### Specification

the `npm bin` command no longer works since it has been deprecated. This means our `shell.nix` no longer adds our bin commands for the project to the local environment. This needs to be fixed for some of our repos. I think any repo that defines bin commands in the package.json?

To fix this the following changes need to be replicated. https://github.com/MatrixAI/Polykey/commit/78a9faa6119a190174c3a880679b9812104ecefa

### Additional context

* https://github.com/MatrixAI/Polykey/commit/78a9faa6119a190174c3a880679b9812104ecefa

### Tasks

* [x] 1. Determine relevant repos
* [x] 2. Fix remaining repos
   - [x] js-db
   - [x] js-encryptedfs

**Comment by CMCDragonkai** [comment]
All repos needs to fixed. We are using `npm bin` in all repos.

**Comment by CMCDragonkai** [comment]
Including `TypeScript-Demo-Lib`.

@amydevs when you are working on any of the repos, you should fix them when you see them too.

**Comment by CMCDragonkai** [comment]
I've done it for `TypeScript-Demo-Lib`. Also for the feature branch in `js-quic`.

@amydevs needs to do it for the new `js-mdns`.

**Comment by CMCDragonkai** [comment]
Done for `js-async-cancellable` and `js-contexts`.

@amydevs any update here?

**Comment by CMCDragonkai** [comment]
Done for `js-async-init`.

**Comment by CMCDragonkai** [comment]
Done for `js-resources`.

**Comment by CMCDragonkai** [comment]
Not yet done for `js-errors`.

**Comment by CMCDragonkai** [comment]
Done for `js-timer` and `js-async-locks`.

**Comment by CMCDragonkai** [comment]
@amydevs can you identify that this is going to be done for `js-mdns`.

**Comment by CMCDragonkai** [comment]
Done for `js-errors`.

**Comment by CMCDragonkai** [comment]
TBD:

1. js-db
2. js-encryptedfs
3. js-id
4. js-workers
5. js-logger
5. Polykey

**Comment by CMCDragonkai** [comment]
@amydevs Do you see this notification now?

**Comment by amydevs** [comment]
> @amydevs can you identify that this is going to be done for `js-mdns`.

done for `js-mdns`

**Comment by CMCDragonkai** [comment]
I've done for `js-id` and I upgraded the repo to match the project structure we have in other repos now, it was still on a very old version. It's released as a new version 3.3.6.

**Comment by CMCDragonkai** [comment]
I've done it for `js-workers` and also updated dependencies and released 1.3.7.

**Comment by CMCDragonkai** [comment]
Done for js-logger.

**Comment by CMCDragonkai** [comment]
Remaining repos is js-db and js-encryptedfs, these 2 use quite a few changes... so it would be interesting to see how they play out.

**Comment by CMCDragonkai** [comment]
For js-db, it is being tracked in https://github.com/MatrixAI/js-db/pull/62.

The js-encryptedfs should be a simple upgrade, but it does depend on the js-db being fixed first.

Afterwards, this can be closed.

**Comment by CMCDragonkai** [comment]
Was done here: https://github.com/MatrixAI/js-encryptedfs/pull/80. Will be released as 3.5.7.

All libraries done. Closing this. Well except the TypeScript Demo native but that's not really relevant anymore with js-db and js-quic being representative native projects.

**Comment by CMCDragonkai** [comment]
@tegefaulkes Polykey deps will need to be all updated however all libraries should be updated with the latest now and confirmed to work on node v18.
