### ISSUE TITLE
Prevent webpack from compiling lib code thrice for agent/cli/lib

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#54]
Webpack currently has three outputs: a file each for the lib, cli and agent. The core lib code is compiled in all three of these outputs and that is unnecessary. we need to find some way to separate them out.
Here is a useful gist: https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693

**Comment by CMCDragonkai** [comment]
The lib should be shared. Make lib external with respect to the other 2?

On 7 July 2020 14:29:38 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>Webpack currently has three outputs: a file each for the lib, cli and
>agent. The core lib code is compiled in all three of these outputs and
>that is unnecessary. we need to find some way to separate them out.
>Here is a useful gist:
>https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/54

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Yeah this is a good idea, I think it's best to specify this in the `externals` of each entry point

**Comment by CMCDragonkai** [comment]
The way lib gets imported will need to be rewritten to point to the locally produced artifact. Or... the lib can be its own npm package. That would piggy back off npm to produce this structure sharing we need.

On 7 July 2020 18:49:26 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>Yeah this is a good idea, I think it's best to specify this in the
>`externals` of each entry point
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/54#issuecomment-654699872

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Yeah it was relatively painless with webpack, in the CLI, I have a single relative import that points to the lib dir. All I had to do was add a line in the cli webpack config:
```
...
externals: [
    { "../lib/Polykey": "commonjs ../lib/polykey.js" },
]
...
```
Works just the same as before, reducing its size from 60KiB to 17KiB. Not really a dramatic change but it removes redundancy.
