### ISSUE TITLE
Implement `timeoutMiddleware` and Remove `metadata.authorization` for `src/nodes/agent` Domain

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey#572]
Issue is WIP

### Specification

1. `agentService` is a public service, so it should not have `authorisation`, but in the current implementation, it does. Which is to be altered. 
2. `agentService` currently does not use `timeoutMiddleware`, which it should.

### Additional context

js-rpc has a sister PR which addresses the same issues - https://github.com/MatrixAI/js-rpc/pull/42

### Tasks

1. Remove authorisation from `AgentRPCRequestParams` and `AgentRPCResponseResult`
2. Implement timeoutMiddleware for `agentService`

**Comment by CMCDragonkai** [comment]
What is `AgentService`? Does not make sense here.

**Comment by addievo** [comment]
@CMCDragonkai you asked me to write up this issue, its regarding

```typescript
// Prevent overwriting the metadata type with `Omit<>`
type AgentRPCRequestParams<T extends Record<string, JSONValue> = ObjectEmpty> =
  {
    metadata?: {
      [Key: string]: JSONValue;
    } & Partial<{
      authorization: string;
      timeout: number;
    }>;
  } & Omit<T, 'metadata'>;

// Prevent overwriting the metadata type with `Omit<>`
type AgentRPCResponseResult<T extends Record<string, JSONValue> = ObjectEmpty> =
  {
    metadata?: {
      [Key: string]: JSONValue;
    } & Partial<{
      authorization: string;
      timeout: number;
    }>;
  } & Omit<T, 'metadata'>;

``` 

And the fact that AgentService is a publicly accessible service, consequently it should not have an authorisation field.

**Comment by CMCDragonkai** [comment]
Is `AgentService` actually a class or type? If not don't refer to it in capitalised form.

**Comment by addievo** [comment]
> Is `AgentService` actually a class or type? If not don't refer to it in capitalised form.

It is not a class, this issue has something to do with the `nodes` domain, I don't remember that well, I need to go over this with Brian.

**Comment by CMCDragonkai** [comment]
Then rename the pr title. It's confusing.
