### ISSUE TITLE
NodesListConnections handler is randomly mapping IP addresses as IPv6 mapped IPv4

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey#614]
### Specification

Whilst testing Polykey CLI's `nodes getall` or `nodes connections`, the IP address is getting listed as IPv6 mapped IPv4, this is inaccurate as all the testing has been performed on IPv4 addresses only. 

This behaviour needs to be investigated and consequently resolved.

### Tasks

1. Investigate where this occurs.
2. Investigate why this occurs.
3. Fix mapping.

**Comment by tegefaulkes** [comment]
Looking into this. If the QUICSocket is dual stack and a reverse connection is handled by the `NodeConnectionManager`, the resulting `Host` added to the `NodeGraph` is the `IPV6` mapped `IPv4` address. 

It's a simple fix to convert this back to the `IPv4` form before putting it into the NodeGraph. But I'm unsure if QUIC is mean to be converting these under the hood so we never deal with the mapped form directly? @CMCDragonkai

**Comment by CMCDragonkai** [comment]
I don't think QUIC should do anything too fancy here.
