### ISSUE TITLE
After roughly commit 58, isomorphic git fails to commit again

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#63]
I am getting a strange error with isomorphic git, namely:
```
Invalid checksum in GitIndex buffer: 
expected 0000000000000000000000000000000000000000 but saw b858b0f102cb2dcb25823c1ac7a10796b9a283d6
```
This only occurs after roughly 58 commits and is reliably failing on the 58th commit. I've tested isomorphic git with normal fs and it doesn't seem to be an issue:
```
import os from 'os'
import fs from 'fs'
import path from 'path'
import git from 'isomorphic-git'
import crypto from 'crypto'

/**
 * Returns a 5 character long random string of lower case letters
 */
function randomString(): string {
  return Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 5)
}

async function main() {
  // Initialize new repo
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'checksum-test'))
  await git.init({
    fs,
    dir: tempDir
  })

  for (const n of Array(1000).keys()) {
    // Write random number of random bytes to file
    const randomNumber = 1 + Math.round(Math.random() * 5000)
    const randomBuffer = crypto.randomBytes(randomNumber)
    const randomFilename = randomString()
    fs.writeFileSync(path.join(tempDir, randomFilename), randomBuffer)

    await git.add({
      fs,
      dir: tempDir,
      filepath: randomFilename
    })
    // commit file
    await git.commit({
      fs,
      dir: tempDir,
      message: randomFilename,
      author: {
        name: 'Test'
      }
    })
  }

}

main()
```

So it seems more likely to be an issue with our implementation and use of isomorphic git and not with isomorphic git itself.

**Comment by robert-cronin** [comment]
The full error message for clarity:
```
InternalError: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: 
expected 0000000000000000000000000000000000000000 but saw b858b0f102cb2dcb25823c1ac7a10796b9a283d6
        at Function.fromBuffer (/home/robbie/Documents/github/js-polykey/node_modules/isomorphic-git/index.cjs:610:13) {
      caller: 'git.add',
      name: 'InternalError',
      code: 'InternalError',
      data: {
        message: 'Invalid checksum in GitIndex buffer: expected 0000000000000000000000000000000000000000 but saw b858b0f102cb2dcb25823c1ac7a10796b9a283d6'
```

**Comment by robert-cronin** [comment]
For more background, here is the jest test that is failing:
```
test('parallel write operations are sequentially executed', async done => {
  const vault = await pk.vaultManager.createVault(randomVaultName)
  const writeOps: Promise<void>[] = []
  const expectedHistory: number[] = []
  for (const n of Array(100).keys()) {
    // Get a random number of bytes so each operation might finish earlier than the others
    const randomNumber = 1 + Math.round(Math.random() * 5000)
    const secretBuffer = crypto.randomBytes(randomNumber)
    const writeOp = vault.addSecret(`${n + 1}`, secretBuffer)
    writeOps.push(writeOp)
    expectedHistory.push(n + 1)
  }
  await Promise.all(writeOps)

  const history = (await vault.getVaultHistory()).reverse()
    .map((commit) => {
      const match = commit.match(/([0-9]+)/)
      return (match) ? parseInt(match[0]) : undefined
    })
    .filter((n) => n != undefined)

  expect(history).toEqual(expectedHistory)

  done()
}, 20000)
```
The `addSecret` method:
```
async addSecret(secretName: string, secret: Buffer): Promise<void> {
  const release = await this.mutex.acquire()
  try {
    // Check if secret already exists
    if (this.secrets.has(secretName)) {
      throw Error('Secret already exists, try updating it instead.')
    }
    const writePath = Path.join(this.vaultPath, secretName)
    // Write secret
    await this.efs.promises.writeFile(writePath, secret, {})
    // Update secrets map
    this.secrets.set(secretName, secret)
    // Auto commit message
    await this.commitChanges(`Add secret: ${secretName}`, secretName, 'added')
  } catch (error) {
    release()
    console.log(error);

    throw error
  } finally {
    release()
  }
}
```
This then calls `commitChanges`:
```
private async commitChanges(message: string, secretName: string, action: 'added' | 'modified' | 'removed'): Promise<string> {
  if (action == 'removed') {
    await git.remove({
      fs: { promises: this.efs.promises },
      dir: this.vaultPath,
      filepath: secretName
    })
  } else {
    await git.add({
      fs: { promises: this.efs.promises },
      dir: this.vaultPath,
      filepath: secretName
    })
  }

  return await git.commit({
    fs: { promises: this.efs.promises },
    dir: this.vaultPath,
    author: {
      name: this.name
    },
    message: message
  })
}
```

**Comment by CMCDragonkai** [comment]
These sorts of bugs tell us that we need to use a fuzzer or quickcheck equivalent.

On 20 July 2020 14:46:58 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>I am getting a strange error with isomorphic git, namely:
>```
>Invalid checksum in GitIndex buffer: 
>expected 0000000000000000000000000000000000000000 but saw
>b858b0f102cb2dcb25823c1ac7a10796b9a283d6
>```
>This only occurs after roughly 58 commits and is reliably failing on
>the 58th commit. I've tested isomorphi git with normal fs and it
>doesn't seem to be an issue:
>```
>import os from 'os'
>import fs from 'fs'
>import path from 'path'
>import git from 'isomorphic-git'
>import crypto from 'crypto'
>
>/**
> * Returns a 5 character long random string of lower case letters
> */
>function randomString(): string {
> return Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 5)
>}
>
>async function main() {
>  // Initialize new repo
>const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'checksum-test'))
>  await git.init({
>    fs,
>    dir: tempDir
>  })
>
>  for (const n of Array(1000).keys()) {
>    // Write random number of random bytes to file
>    const randomNumber = 1 + Math.round(Math.random() * 5000)
>    const randomBuffer = crypto.randomBytes(randomNumber)
>    const randomFilename = randomString()
>    fs.writeFileSync(path.join(tempDir, randomFilename), randomBuffer)
>
>    await git.add({
>      fs,
>      dir: tempDir,
>      filepath: randomFilename
>    })
>    // commit file
>    await git.commit({
>      fs,
>      dir: tempDir,
>      message: randomFilename,
>      author: {
>        name: 'Test'
>      }
>    })
>  }
>
>}
>
>main()
>```
>
>So it seems more likely to be an issue with our implementation and use
>of isomorphic git and not with isomorphic git itself.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/63

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Example of a quickcheck that can be integrated into jest: https://github.com/dubzzz/fast-check

This allows us to quickly do property testing.

I'm not sure how complex it can fuzz, but generally with these sorts of things, you could "enumerate" legal sequences of operations. A command pattern basically.

Then test all the legal sequences of commands and then check if the system passes all of them.

This avoids needing us to think and code of every single possible legal operation sequence.

**Comment by CMCDragonkai** [comment]
@robert-cronin is this still an error?

**Comment by CMCDragonkai** [comment]
This really needs to be solved before general release.

**Comment by robert-cronin** [comment]
Yes this is still an error, I had hoped there would be some guidance from isomorphic git repo but there hasn't been any update since I posted this issue in July: https://github.com/isomorphic-git/isomorphic-git/issues/1198

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
