### ISSUE TITLE
Vaults clone with name of a vault already existing fails

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey#652]
### Specification

If a vault already exists with the same name as the one being cloned, polykey throws "undefined". 

This is a bug and the clone option needs to be expanded with the proper errors to demonstrate why it is failing and expand the clone option to allow force cloning.

### Tasks

1. Fix vaultManager
2. Fix handler
3. Fix CLI

Related https://github.com/MatrixAI/Polykey-CLI/issues/73

**Comment by CMCDragonkai** [comment]
Link to a new issue with proper spec of how this is to be sorted out more efficiently.

**Comment by tegefaulkes** [comment]
New issue created at https://github.com/MatrixAI/Polykey/issues/672
