### ISSUE TITLE
npm release in gitlab-ci doesn't work

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#66]
I am getting the following error when trying to deploy automatically with `npm publish`:
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/js-polykey - Not found
npm ERR! 404 
npm ERR! 404  'js-polykey@0.0.10' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by robert-cronin** [comment]
might have some luck here: https://docs.gitlab.com/ee/user/packages/npm_registry/#uploading-packages

**Comment by CMCDragonkai** [comment]
Pretty sure it should just be `polykey`, not `js-polykey` right? The `js-` prefix was only intended to disambiguate for our libraries with the same name on Github.

However, we may be using our vendor prefix `@matrixai` for many other things.

I don't think `Polykey` main app can be distributed on npm.

**Comment by robert-cronin** [comment]
there was an issue with having the pname the same as one of the dependencies in nixos. it's not case sensitive either so it's not a simple matter of having polykey for the lib via npm and PolyKey for the GUI via nixpkgs

**Comment by robert-cronin** [comment]
@matrixai/polykey should disambiguate. Shall I rename it to that then and deprecate [js-polykey](https://www.npmjs.com/package/js-polykey)?

**Comment by CMCDragonkai** [comment]
Yes

On 12 August 2020 03:05:24 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>@matrixai/polykey should disambiguate. Shall I rename it to that then
>and deprecate [js-polykey](https://www.npmjs.com/package/js-polykey)?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/66#issuecomment-672098469

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
