### ISSUE TITLE
Pseudo file systems interface

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#72]
Adding another interface when I was thinking about integration into Matrix OS and NixOS.

See: https://en.wikipedia.org/wiki/Synthetic_file_system

Basically we can present certain secrets to the user through presenting a pseudo filesystem and automatically mounting it somewhere.

Of course, this involves things like FUSE since Polykey is likely run by non-root user.

On the other hand running as root is also possible and that may be relevant to our Matrix OS system (thus managing root level secrets).

Windows will need to do something different like https://dokan-dev.github.io/. That's what keybase uses.

**Comment by CMCDragonkai** [comment]
Out of all interfaces, this one is the lowest priority. It is also the most complex.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
