### ISSUE TITLE
Access Audit Log

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#74]
Any access to secret vaults should be logged, and maybe we can use the atime of files/directories. I dont remember how directory atimes are updated.

Access logs can go into a file, or go to stderr.

Going to stderr allows users to integrate external audit logging systems.

Going to file means pk will then show the logs over time.

It also means logging format should be structured. There is a syslog standard but... opentracing might an interesting idea here.

This is just for research now, not part of MVP.

**Comment by CMCDragonkai** [comment]
It can show who/what/when/how.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
