### ISSUE TITLE
Move docs directory to gh-pages

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#75]
Instead of every PR generating docs which is now a pain. We should move these to the gh-pages branch so they can be presented on the github pages website.

Furthermore, pushing to gh-pages branch can be done by the CI/CD automatically.

It's basically pushing to the gh-pages branch, so the CI/CD just need to be configured with the relevant key to do so.

Would make it easier for me to review the PRs.

**Comment by robert-cronin** [comment]
apparently the best way to deploy to the `gh-pages` branch is via a [github deploy token](https://docs.github.com/en/developers/overview/managing-deploy-keys)

**Comment by robert-cronin** [comment]
docs are now viewable from https://matrixai.github.io/js-polykey/
this issue remains open due to the requirement to get CI/CD releasing docs automatically.

**Comment by CMCDragonkai** [comment]
Looks really nice.

**Comment by CMCDragonkai** [comment]
I'm going to mark this as done. We can create a separate issue for auto-generation later. That will be in issue in TypeScript-Demo-Lib, and not here.
