### ISSUE TITLE
Vault Schema

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#76]
Vault schemas describe the content of a vault and limits the media types that is allowed to go into the vault files.

A vault can have an attached schema. When a schema is attached, it autogenerates the marshaling code and acts like a validation layer.

This allows us to represent things like credit card data, or username password combos, or tls certificates, public and private keys.

Can reuse ideas from openapi, json schema and semantic web.

For research now, not priority.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
