### ISSUE TITLE
Polykey Agent Design

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#77]
I've always disliked it when programs create their own subshell/repl, it makes it difficult to integrate. This is OK, if the subshell is presenting a totally different world with different semantics, but with Polykey CLI it should just present a FS interface, and standard Unix tooling can work on it easily.

So if we are not creating a sub-shell within the normal shell, we need to instead integrate our "session" into the normal shell.

So that means that during our installation we also end up installing an agent. This is only needed during our CLI phase. However later I want re-use that agent for the GUI as well. So then it acts as a like taskbar agent in Windows and Mac, for Linux it would a user-level service. I would expect that the client and agent both integrate the js-polykey library.

So what does that mean? Well, it is possible for a single desktop to be running multiple keynodes. You can have a keynode in `~/.polykey1` and another keynode in `~/.polykey2`. No problem with this.

Then the agent for now can keep the "login" session for each keynode that it knows about. So a user-level agent keeps track of keynodes for that user on Unix system (or Windows). But a root level agent would keep track of keynodes on the entire machine. But one could also have an agent within a nix-shell keeping track of just keynodes within its domain. So basically multiple agents may exist at the same time (this will make it easier to debug the agent and use it in infrastructure).

So from this point onwards, every polykey operation requires the client which is the `polykey` app to be authenticated. This means either asking for the password to unlock the stored private key, or asking for the private key if that is not stored.

However like the `sudo` command, as soon as we have authenticated once for any operation, we can then save that authentication to the polykey agent such that subsequent operations do not need to be reauthenticated.

We can do the above automatically or on the basis of some switch. But for prototyping purposes, let's do this automatically.

The session can have a time-expiry, and this can be refreshed on every operation. We can this configurable, but for now let's just fix to 1 hr.

The way in which polykey clients connect to the agent can be done similar to how ssh-agent or gpg agent is utilised. A standard environment variable pointing to some sort of socket that exists somewhere. See `SSH_AUTH_SOCK`.

Note that developing this agent also leads to interesting ideas about agent forwarding similar to how SSH works. However I want to leave this out for now, but it does pertain to another integration point, where in this the integration point is with SSH.

**Comment by robert-cronin** [comment]
The points discussed here are largely addressed already in the agent code. What is left is the expiry on the auth for unlocking a polykey node. This will be up to the agent to control and it can re-lock after a specific time period.

**Comment by robert-cronin** [comment]
the timeout functionality for locking the agent is now implemented and defaults to 15 minutes but can also be specified on the cli: 
`pk agent unlock -pp passphrase -t 60 #unlocked for 1 hour`

**Comment by robert-cronin** [comment]
this functionality is locked to the KeyManager and is always on for security purposes.

**Comment by robert-cronin** [comment]
Its a timeout based on inactivity so as long as a user keeps using polykey, it won't lock
