### ISSUE TITLE
Secret editor on the CLI

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#78]
This issue is based on https://github.com/MatrixAI/js-polykey/issues/30#issuecomment-483919937
Basically we want to be able to do something like
```
pk secrets ed vault1:secret1
```
and have it open in the default editor.

Here is how you do it in shell:
```
tmpfile=$(mktemp /tmp/abc.XXXXXX)
exec {fd}<> "$tmpfile"
rm -f "$tmpfile"
vim "/proc/self/fd/$fd"
cat <&${fd}
```
we just need to figure out how to have it triggered in JavaScript

**Comment by CMCDragonkai** [comment]
Here you would use `$EDITOR` as the default editor. If it is not defined we may just error out.

On 12 August 2020 13:18:15 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>This issue is based on
>https://github.com/MatrixAI/js-polykey/issues/30#issuecomment-483919937
>Basically we want to be able to do something like
>```
>pk secrets ed vault1:secret1
>```
>and have it open in the default editor.
>
>Here is how you do it in shell:
>```
>tmpfile=$(mktemp /tmp/abc.XXXXXX)
>exec {fd}<> "$tmpfile"
>rm -f "$tmpfile"
>vim "/proc/self/fd/$fd"
>cat <&${fd}
>```
>we just need to figure out how to have it triggered in JavaScript
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/78

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Oh this is easy. Create a temporary file, open a fd to it, delete it the file on fs, write the secret contents to file, then open an editor the fd (which is read/write).

Note that the editor may be making a copy so we can't guarantee that they are editing the temporary file.

But when saved you can then take that fd and seek to beginning and then save to the secret.

However this is not that important yet so we can put this at lower priority.

On 12 August 2020 13:18:15 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>This issue is based on
>https://github.com/MatrixAI/js-polykey/issues/30#issuecomment-483919937
>Basically we want to be able to do something like
>```
>pk secrets ed vault1:secret1
>```
>and have it open in the default editor.
>
>Here is how you do it in shell:
>```
>tmpfile=$(mktemp /tmp/abc.XXXXXX)
>exec {fd}<> "$tmpfile"
>rm -f "$tmpfile"
>vim "/proc/self/fd/$fd"
>cat <&${fd}
>```
>we just need to figure out how to have it triggered in JavaScript
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/issues/78

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
