### ISSUE TITLE
Integrating PKCS #11 standard for accessing HSM

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#80]
Polykey could be used to access HSM.

In particular we can maintain some information in available HSM on the target platform instead of just sitting in in `~/.polykey`.

Or perhaps even an entire keynode could be put into the HSM. Right now we just need a posix filesystem.

Not entirely sure, but I suspect support of HSM would enable alot more corporate usage. And this includes TPM, ARM secure enclaves, ios/android, and usb dongles and special keys like yubikey?

* https://github.com/orygin10/tpmfs
* https://security.stackexchange.com/questions/124338/right-way-to-use-the-tpm-for-full-disk-encryption

Not a priority atm.

**Comment by CMCDragonkai** [comment]
* https://github.com/PeculiarVentures/graphene
* https://github.com/PeculiarVentures/node-webcrypto-p11

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
