### ISSUE TITLE
Exception Hierarchy for Structured Error Handling

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#82]
We need to create a new exception hierarchy for the library and CLI commands. This will allow structured error handling for Polykey.

VirtualFS does this with `errno` library and it tells the user/developer something similar to a trace (which function called it and what error code it was)

Linked to https://github.com/MatrixAI/PolyKey/issues/51

**Comment by CMCDragonkai** [comment]
The reason I used errno in js-virtualfs was to match the errors from 
POSIX filesystems.

In js-polykey there's no analogue. So a custom exception hierarchy is fine.

Make sure to use the `ts-custom-error` library to do this though.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
