### ISSUE TITLE
Interactive Response Latency

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#88]
One of our acceptance tests can be for interactive response latency:

https://www.pubnub.com/blog/how-fast-is-realtime-human-perception-and-technology/

Using opentracing techniques we can even isolate where the latency comes from in our applications.

I suspect optimizing our cryptographic performance will be important. This includes making use of parallel thread pool to do the cryptography asynchronously.

Thread pinning is another idea.

We might investigate the usage of webassembly as well.

Important links:

* https://medium.com/cubbit/how-to-build-a-crypto-isomorphic-library-with-javascript-and-webassembly-6fc7aa708437
* https://emscripten.org/docs/compiling/WebAssembly.html
* https://github.com/cubbit/enigma - uses emscripten to compile to web assembly (although only usable on browsers), this may be important for different platforms... not sure if we can access native crypto on other platforms to achieve this
* https://stackoverflow.com/questions/48891593/webcryptoapi-vs-webassembly-encryption-module - perhaps it may be a better idea to try to delegate to platform specific crypto
* https://github.com/jedisct1/wasm-crypto

I think opentracing will allow us to measure latency of all API operations based on #3 

We will only know what to use by measuring and having quantified measurements on our operations.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
