### ISSUE TITLE
Delay Tolerant Networking

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#89]
We expect Polykey keynodes to go online and offline all the time. While it appears as soon as it is possible we can share vaults between keynodes. I wonder if we take some ideas from DTN:

https://en.wikipedia.org/wiki/Delay-tolerant_networking

It seems that it should mean that it would be possible to pause communication and when re-established continue working.

Just research for now.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
