### ISSUE TITLE
Explore removing webpack

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#93]
As done in typescript-demo-lib the webpack shouldn't be needed in cli and library applications.

But then path resolution requires an alternative such as module-alias.

In the src we have the cli scripts that are compiled. There can't use the module alias as it overrides typescripts path resolution. Instead you can add module alias afterwards, perhaps as an extra js script on top.

Anyway no bundling here is actually more efficient.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
