### ISSUE TITLE
xstate model for communication transitions

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#96]
We can use xstate to model the communication transitions in polykey.

linked comment: https://github.com/MatrixAI/js-polykey/pull/84#discussion_r486280990

**Comment by CMCDragonkai** [comment]
Make sure to share notes with @DrFacepalm

**Comment by robert-cronin** [comment]
We now have xstate models for most of the important transitions in polykey, including the DHT, KeyManager unlocked/locked, peer connections while pulling/cloning vaults etc.
There are certainly more things to model but this should be done when we are ready to integrate xstate as an implementation feature of polykey.
